/**
 * División político-administrativa de Colombia (DIVIPOLA), vendorizada desde
 * los datasets oficiales de datos.gov.co / DANE:
 * https://www.datos.gov.co/Mapas-Nacionales/DIVIPOLA-C-digos-departamentos/vcjz-niiq
 * https://www.datos.gov.co/Mapas-Nacionales/DIVIPOLA-C-digos-municipios/gdxc-w37w
 * Descargado 2026-09-04. 33 departamentos, 1122 municipios.
 * Nombres normalizados a título (el dataset original viene en MAYÚSCULAS);
 * los códigos son textuales tal cual DIVIPOLA (con ceros a la izquierda).
 * No se edita a mano: se vuelve a descargar y regenerar si el DANE publica un
 * cambio de división territorial.
 */
export interface Departamento {
  readonly codigo: string;
  readonly nombre: string;
}

export interface Municipio {
  readonly codigoDepartamento: string;
  readonly codigo: string;
  readonly nombre: string;
}

export const DEPARTAMENTOS: readonly Departamento[] = [
  { codigo: '05', nombre: 'Antioquia' },
  { codigo: '08', nombre: 'Atlántico' },
  { codigo: '11', nombre: 'Bogotá, D.C.' },
  { codigo: '13', nombre: 'Bolívar' },
  { codigo: '15', nombre: 'Boyacá' },
  { codigo: '17', nombre: 'Caldas' },
  { codigo: '18', nombre: 'Caquetá' },
  { codigo: '19', nombre: 'Cauca' },
  { codigo: '20', nombre: 'Cesar' },
  { codigo: '23', nombre: 'Córdoba' },
  { codigo: '25', nombre: 'Cundinamarca' },
  { codigo: '27', nombre: 'Chocó' },
  { codigo: '41', nombre: 'Huila' },
  { codigo: '44', nombre: 'La Guajira' },
  { codigo: '47', nombre: 'Magdalena' },
  { codigo: '50', nombre: 'Meta' },
  { codigo: '52', nombre: 'Nariño' },
  { codigo: '54', nombre: 'Norte de Santander' },
  { codigo: '63', nombre: 'Quindío' },
  { codigo: '66', nombre: 'Risaralda' },
  { codigo: '68', nombre: 'Santander' },
  { codigo: '70', nombre: 'Sucre' },
  { codigo: '73', nombre: 'Tolima' },
  { codigo: '76', nombre: 'Valle del Cauca' },
  { codigo: '81', nombre: 'Arauca' },
  { codigo: '85', nombre: 'Casanare' },
  { codigo: '86', nombre: 'Putumayo' },
  { codigo: '88', nombre: 'Archipiélago de San Andrés, Providencia y Santa Catalina' },
  { codigo: '91', nombre: 'Amazonas' },
  { codigo: '94', nombre: 'Guainía' },
  { codigo: '95', nombre: 'Guaviare' },
  { codigo: '97', nombre: 'Vaupés' },
  { codigo: '99', nombre: 'Vichada' },
];

export const MUNICIPIOS: readonly Municipio[] = [
  { codigoDepartamento: '05', codigo: '05001', nombre: 'Medellín' },
  { codigoDepartamento: '05', codigo: '05002', nombre: 'Abejorral' },
  { codigoDepartamento: '05', codigo: '05004', nombre: 'Abriaquí' },
  { codigoDepartamento: '05', codigo: '05021', nombre: 'Alejandría' },
  { codigoDepartamento: '05', codigo: '05030', nombre: 'Amagá' },
  { codigoDepartamento: '05', codigo: '05031', nombre: 'Amalfi' },
  { codigoDepartamento: '05', codigo: '05034', nombre: 'Andes' },
  { codigoDepartamento: '05', codigo: '05036', nombre: 'Angelópolis' },
  { codigoDepartamento: '05', codigo: '05038', nombre: 'Angostura' },
  { codigoDepartamento: '05', codigo: '05040', nombre: 'Anorí' },
  { codigoDepartamento: '05', codigo: '05042', nombre: 'Santa Fé de Antioquia' },
  { codigoDepartamento: '05', codigo: '05044', nombre: 'Anzá' },
  { codigoDepartamento: '05', codigo: '05045', nombre: 'Apartadó' },
  { codigoDepartamento: '05', codigo: '05051', nombre: 'Arboletes' },
  { codigoDepartamento: '05', codigo: '05055', nombre: 'Argelia' },
  { codigoDepartamento: '05', codigo: '05059', nombre: 'Armenia' },
  { codigoDepartamento: '05', codigo: '05079', nombre: 'Barbosa' },
  { codigoDepartamento: '05', codigo: '05086', nombre: 'Belmira' },
  { codigoDepartamento: '05', codigo: '05088', nombre: 'Bello' },
  { codigoDepartamento: '05', codigo: '05091', nombre: 'Betania' },
  { codigoDepartamento: '05', codigo: '05093', nombre: 'Betulia' },
  { codigoDepartamento: '05', codigo: '05101', nombre: 'Ciudad Bolívar' },
  { codigoDepartamento: '05', codigo: '05107', nombre: 'Briceño' },
  { codigoDepartamento: '05', codigo: '05113', nombre: 'Buriticá' },
  { codigoDepartamento: '05', codigo: '05120', nombre: 'Cáceres' },
  { codigoDepartamento: '05', codigo: '05125', nombre: 'Caicedo' },
  { codigoDepartamento: '05', codigo: '05129', nombre: 'Caldas' },
  { codigoDepartamento: '05', codigo: '05134', nombre: 'Campamento' },
  { codigoDepartamento: '05', codigo: '05138', nombre: 'Cañasgordas' },
  { codigoDepartamento: '05', codigo: '05142', nombre: 'Caracolí' },
  { codigoDepartamento: '05', codigo: '05145', nombre: 'Caramanta' },
  { codigoDepartamento: '05', codigo: '05147', nombre: 'Carepa' },
  { codigoDepartamento: '05', codigo: '05148', nombre: 'El Carmen de Viboral' },
  { codigoDepartamento: '05', codigo: '05150', nombre: 'Carolina' },
  { codigoDepartamento: '05', codigo: '05154', nombre: 'Caucasia' },
  { codigoDepartamento: '05', codigo: '05172', nombre: 'Chigorodó' },
  { codigoDepartamento: '05', codigo: '05190', nombre: 'Cisneros' },
  { codigoDepartamento: '05', codigo: '05197', nombre: 'Cocorná' },
  { codigoDepartamento: '05', codigo: '05206', nombre: 'Concepción' },
  { codigoDepartamento: '05', codigo: '05209', nombre: 'Concordia' },
  { codigoDepartamento: '05', codigo: '05212', nombre: 'Copacabana' },
  { codigoDepartamento: '05', codigo: '05234', nombre: 'Dabeiba' },
  { codigoDepartamento: '05', codigo: '05237', nombre: 'Donmatías' },
  { codigoDepartamento: '05', codigo: '05240', nombre: 'Ebéjico' },
  { codigoDepartamento: '05', codigo: '05250', nombre: 'El Bagre' },
  { codigoDepartamento: '05', codigo: '05264', nombre: 'Entrerríos' },
  { codigoDepartamento: '05', codigo: '05266', nombre: 'Envigado' },
  { codigoDepartamento: '05', codigo: '05282', nombre: 'Fredonia' },
  { codigoDepartamento: '05', codigo: '05284', nombre: 'Frontino' },
  { codigoDepartamento: '05', codigo: '05306', nombre: 'Giraldo' },
  { codigoDepartamento: '05', codigo: '05308', nombre: 'Girardota' },
  { codigoDepartamento: '05', codigo: '05310', nombre: 'Gómez Plata' },
  { codigoDepartamento: '05', codigo: '05313', nombre: 'Granada' },
  { codigoDepartamento: '05', codigo: '05315', nombre: 'Guadalupe' },
  { codigoDepartamento: '05', codigo: '05318', nombre: 'Guarne' },
  { codigoDepartamento: '05', codigo: '05321', nombre: 'Guatapé' },
  { codigoDepartamento: '05', codigo: '05347', nombre: 'Heliconia' },
  { codigoDepartamento: '05', codigo: '05353', nombre: 'Hispania' },
  { codigoDepartamento: '05', codigo: '05360', nombre: 'Itagüí' },
  { codigoDepartamento: '05', codigo: '05361', nombre: 'Ituango' },
  { codigoDepartamento: '05', codigo: '05364', nombre: 'Jardín' },
  { codigoDepartamento: '05', codigo: '05368', nombre: 'Jericó' },
  { codigoDepartamento: '05', codigo: '05376', nombre: 'La Ceja' },
  { codigoDepartamento: '05', codigo: '05380', nombre: 'La Estrella' },
  { codigoDepartamento: '05', codigo: '05390', nombre: 'La Pintada' },
  { codigoDepartamento: '05', codigo: '05400', nombre: 'La Unión' },
  { codigoDepartamento: '05', codigo: '05411', nombre: 'Liborina' },
  { codigoDepartamento: '05', codigo: '05425', nombre: 'Maceo' },
  { codigoDepartamento: '05', codigo: '05440', nombre: 'Marinilla' },
  { codigoDepartamento: '05', codigo: '05467', nombre: 'Montebello' },
  { codigoDepartamento: '05', codigo: '05475', nombre: 'Murindó' },
  { codigoDepartamento: '05', codigo: '05480', nombre: 'Mutatá' },
  { codigoDepartamento: '05', codigo: '05483', nombre: 'Nariño' },
  { codigoDepartamento: '05', codigo: '05490', nombre: 'Necoclí' },
  { codigoDepartamento: '05', codigo: '05495', nombre: 'Nechí' },
  { codigoDepartamento: '05', codigo: '05501', nombre: 'Olaya' },
  { codigoDepartamento: '05', codigo: '05541', nombre: 'Peñol' },
  { codigoDepartamento: '05', codigo: '05543', nombre: 'Peque' },
  { codigoDepartamento: '05', codigo: '05576', nombre: 'Pueblorrico' },
  { codigoDepartamento: '05', codigo: '05579', nombre: 'Puerto Berrío' },
  { codigoDepartamento: '05', codigo: '05585', nombre: 'Puerto Nare' },
  { codigoDepartamento: '05', codigo: '05591', nombre: 'Puerto Triunfo' },
  { codigoDepartamento: '05', codigo: '05604', nombre: 'Remedios' },
  { codigoDepartamento: '05', codigo: '05607', nombre: 'Retiro' },
  { codigoDepartamento: '05', codigo: '05615', nombre: 'Rionegro' },
  { codigoDepartamento: '05', codigo: '05628', nombre: 'Sabanalarga' },
  { codigoDepartamento: '05', codigo: '05631', nombre: 'Sabaneta' },
  { codigoDepartamento: '05', codigo: '05642', nombre: 'Salgar' },
  { codigoDepartamento: '05', codigo: '05647', nombre: 'San Andrés de Cuerquía' },
  { codigoDepartamento: '05', codigo: '05649', nombre: 'San Carlos' },
  { codigoDepartamento: '05', codigo: '05652', nombre: 'San Francisco' },
  { codigoDepartamento: '05', codigo: '05656', nombre: 'San Jerónimo' },
  { codigoDepartamento: '05', codigo: '05658', nombre: 'San José de la Montaña' },
  { codigoDepartamento: '05', codigo: '05659', nombre: 'San Juan de Urabá' },
  { codigoDepartamento: '05', codigo: '05660', nombre: 'San Luis' },
  { codigoDepartamento: '05', codigo: '05664', nombre: 'San Pedro de los Milagros' },
  { codigoDepartamento: '05', codigo: '05665', nombre: 'San Pedro de Urabá' },
  { codigoDepartamento: '05', codigo: '05667', nombre: 'San Rafael' },
  { codigoDepartamento: '05', codigo: '05670', nombre: 'San Roque' },
  { codigoDepartamento: '05', codigo: '05674', nombre: 'San Vicente Ferrer' },
  { codigoDepartamento: '05', codigo: '05679', nombre: 'Santa Bárbara' },
  { codigoDepartamento: '05', codigo: '05686', nombre: 'Santa Rosa de Osos' },
  { codigoDepartamento: '05', codigo: '05690', nombre: 'Santo Domingo' },
  { codigoDepartamento: '05', codigo: '05697', nombre: 'El Santuario' },
  { codigoDepartamento: '05', codigo: '05736', nombre: 'Segovia' },
  { codigoDepartamento: '05', codigo: '05756', nombre: 'Sonsón' },
  { codigoDepartamento: '05', codigo: '05761', nombre: 'Sopetrán' },
  { codigoDepartamento: '05', codigo: '05789', nombre: 'Támesis' },
  { codigoDepartamento: '05', codigo: '05790', nombre: 'Tarazá' },
  { codigoDepartamento: '05', codigo: '05792', nombre: 'Tarso' },
  { codigoDepartamento: '05', codigo: '05809', nombre: 'Titiribí' },
  { codigoDepartamento: '05', codigo: '05819', nombre: 'Toledo' },
  { codigoDepartamento: '05', codigo: '05837', nombre: 'Turbo' },
  { codigoDepartamento: '05', codigo: '05842', nombre: 'Uramita' },
  { codigoDepartamento: '05', codigo: '05847', nombre: 'Urrao' },
  { codigoDepartamento: '05', codigo: '05854', nombre: 'Valdivia' },
  { codigoDepartamento: '05', codigo: '05856', nombre: 'Valparaíso' },
  { codigoDepartamento: '05', codigo: '05858', nombre: 'Vegachí' },
  { codigoDepartamento: '05', codigo: '05861', nombre: 'Venecia' },
  { codigoDepartamento: '05', codigo: '05873', nombre: 'Vigía del Fuerte' },
  { codigoDepartamento: '05', codigo: '05885', nombre: 'Yalí' },
  { codigoDepartamento: '05', codigo: '05887', nombre: 'Yarumal' },
  { codigoDepartamento: '05', codigo: '05890', nombre: 'Yolombó' },
  { codigoDepartamento: '05', codigo: '05893', nombre: 'Yondó' },
  { codigoDepartamento: '05', codigo: '05895', nombre: 'Zaragoza' },
  { codigoDepartamento: '08', codigo: '08001', nombre: 'Barranquilla' },
  { codigoDepartamento: '08', codigo: '08078', nombre: 'Baranoa' },
  { codigoDepartamento: '08', codigo: '08137', nombre: 'Campo de la Cruz' },
  { codigoDepartamento: '08', codigo: '08141', nombre: 'Candelaria' },
  { codigoDepartamento: '08', codigo: '08296', nombre: 'Galapa' },
  { codigoDepartamento: '08', codigo: '08372', nombre: 'Juan de Acosta' },
  { codigoDepartamento: '08', codigo: '08421', nombre: 'Luruaco' },
  { codigoDepartamento: '08', codigo: '08433', nombre: 'Malambo' },
  { codigoDepartamento: '08', codigo: '08436', nombre: 'Manatí' },
  { codigoDepartamento: '08', codigo: '08520', nombre: 'Palmar de Varela' },
  { codigoDepartamento: '08', codigo: '08549', nombre: 'Piojó' },
  { codigoDepartamento: '08', codigo: '08558', nombre: 'Polonuevo' },
  { codigoDepartamento: '08', codigo: '08560', nombre: 'Ponedera' },
  { codigoDepartamento: '08', codigo: '08573', nombre: 'Puerto Colombia' },
  { codigoDepartamento: '08', codigo: '08606', nombre: 'Repelón' },
  { codigoDepartamento: '08', codigo: '08634', nombre: 'Sabanagrande' },
  { codigoDepartamento: '08', codigo: '08638', nombre: 'Sabanalarga' },
  { codigoDepartamento: '08', codigo: '08675', nombre: 'Santa Lucía' },
  { codigoDepartamento: '08', codigo: '08685', nombre: 'Santo Tomás' },
  { codigoDepartamento: '08', codigo: '08758', nombre: 'Soledad' },
  { codigoDepartamento: '08', codigo: '08770', nombre: 'Suan' },
  { codigoDepartamento: '08', codigo: '08832', nombre: 'Tubará' },
  { codigoDepartamento: '08', codigo: '08849', nombre: 'Usiacurí' },
  { codigoDepartamento: '11', codigo: '11001', nombre: 'Bogotá, D.C.' },
  { codigoDepartamento: '13', codigo: '13001', nombre: 'Cartagena de Indias' },
  { codigoDepartamento: '13', codigo: '13006', nombre: 'Achí' },
  { codigoDepartamento: '13', codigo: '13030', nombre: 'Altos del Rosario' },
  { codigoDepartamento: '13', codigo: '13042', nombre: 'Arenal' },
  { codigoDepartamento: '13', codigo: '13052', nombre: 'Arjona' },
  { codigoDepartamento: '13', codigo: '13062', nombre: 'Arroyohondo' },
  { codigoDepartamento: '13', codigo: '13074', nombre: 'Barranco de Loba' },
  { codigoDepartamento: '13', codigo: '13140', nombre: 'Calamar' },
  { codigoDepartamento: '13', codigo: '13160', nombre: 'Cantagallo' },
  { codigoDepartamento: '13', codigo: '13188', nombre: 'Cicuco' },
  { codigoDepartamento: '13', codigo: '13212', nombre: 'Córdoba' },
  { codigoDepartamento: '13', codigo: '13222', nombre: 'Clemencia' },
  { codigoDepartamento: '13', codigo: '13244', nombre: 'El Carmen de Bolívar' },
  { codigoDepartamento: '13', codigo: '13248', nombre: 'El Guamo' },
  { codigoDepartamento: '13', codigo: '13268', nombre: 'El Peñón' },
  { codigoDepartamento: '13', codigo: '13300', nombre: 'Hatillo de Loba' },
  { codigoDepartamento: '13', codigo: '13430', nombre: 'Magangué' },
  { codigoDepartamento: '13', codigo: '13433', nombre: 'Mahates' },
  { codigoDepartamento: '13', codigo: '13440', nombre: 'Margarita' },
  { codigoDepartamento: '13', codigo: '13442', nombre: 'María la Baja' },
  { codigoDepartamento: '13', codigo: '13458', nombre: 'Montecristo' },
  { codigoDepartamento: '13', codigo: '13468', nombre: 'Santa Cruz de Mompox' },
  { codigoDepartamento: '13', codigo: '13473', nombre: 'Morales' },
  { codigoDepartamento: '13', codigo: '13490', nombre: 'Norosí' },
  { codigoDepartamento: '13', codigo: '13549', nombre: 'Pinillos' },
  { codigoDepartamento: '13', codigo: '13580', nombre: 'Regidor' },
  { codigoDepartamento: '13', codigo: '13600', nombre: 'Río Viejo' },
  { codigoDepartamento: '13', codigo: '13620', nombre: 'San Cristóbal' },
  { codigoDepartamento: '13', codigo: '13647', nombre: 'San Estanislao' },
  { codigoDepartamento: '13', codigo: '13650', nombre: 'San Fernando' },
  { codigoDepartamento: '13', codigo: '13654', nombre: 'San Jacinto' },
  { codigoDepartamento: '13', codigo: '13655', nombre: 'San Jacinto del Cauca' },
  { codigoDepartamento: '13', codigo: '13657', nombre: 'San Juan Nepomuceno' },
  { codigoDepartamento: '13', codigo: '13667', nombre: 'San Martín de Loba' },
  { codigoDepartamento: '13', codigo: '13670', nombre: 'San Pablo' },
  { codigoDepartamento: '13', codigo: '13673', nombre: 'Santa Catalina' },
  { codigoDepartamento: '13', codigo: '13683', nombre: 'Santa Rosa' },
  { codigoDepartamento: '13', codigo: '13688', nombre: 'Santa Rosa del Sur' },
  { codigoDepartamento: '13', codigo: '13744', nombre: 'Simití' },
  { codigoDepartamento: '13', codigo: '13760', nombre: 'Soplaviento' },
  { codigoDepartamento: '13', codigo: '13780', nombre: 'Talaigua Nuevo' },
  { codigoDepartamento: '13', codigo: '13810', nombre: 'Tiquisio' },
  { codigoDepartamento: '13', codigo: '13836', nombre: 'Turbaco' },
  { codigoDepartamento: '13', codigo: '13838', nombre: 'Turbaná' },
  { codigoDepartamento: '13', codigo: '13873', nombre: 'Villanueva' },
  { codigoDepartamento: '13', codigo: '13894', nombre: 'Zambrano' },
  { codigoDepartamento: '15', codigo: '15001', nombre: 'Tunja' },
  { codigoDepartamento: '15', codigo: '15022', nombre: 'Almeida' },
  { codigoDepartamento: '15', codigo: '15047', nombre: 'Aquitania' },
  { codigoDepartamento: '15', codigo: '15051', nombre: 'Arcabuco' },
  { codigoDepartamento: '15', codigo: '15087', nombre: 'Belén' },
  { codigoDepartamento: '15', codigo: '15090', nombre: 'Berbeo' },
  { codigoDepartamento: '15', codigo: '15092', nombre: 'Betéitiva' },
  { codigoDepartamento: '15', codigo: '15097', nombre: 'Boavita' },
  { codigoDepartamento: '15', codigo: '15104', nombre: 'Boyacá' },
  { codigoDepartamento: '15', codigo: '15106', nombre: 'Briceño' },
  { codigoDepartamento: '15', codigo: '15109', nombre: 'Buenavista' },
  { codigoDepartamento: '15', codigo: '15114', nombre: 'Busbanzá' },
  { codigoDepartamento: '15', codigo: '15131', nombre: 'Caldas' },
  { codigoDepartamento: '15', codigo: '15135', nombre: 'Campohermoso' },
  { codigoDepartamento: '15', codigo: '15162', nombre: 'Cerinza' },
  { codigoDepartamento: '15', codigo: '15172', nombre: 'Chinavita' },
  { codigoDepartamento: '15', codigo: '15176', nombre: 'Chiquinquirá' },
  { codigoDepartamento: '15', codigo: '15180', nombre: 'Chiscas' },
  { codigoDepartamento: '15', codigo: '15183', nombre: 'Chita' },
  { codigoDepartamento: '15', codigo: '15185', nombre: 'Chitaraque' },
  { codigoDepartamento: '15', codigo: '15187', nombre: 'Chivatá' },
  { codigoDepartamento: '15', codigo: '15189', nombre: 'Ciénega' },
  { codigoDepartamento: '15', codigo: '15204', nombre: 'Cómbita' },
  { codigoDepartamento: '15', codigo: '15212', nombre: 'Coper' },
  { codigoDepartamento: '15', codigo: '15215', nombre: 'Corrales' },
  { codigoDepartamento: '15', codigo: '15218', nombre: 'Covarachía' },
  { codigoDepartamento: '15', codigo: '15223', nombre: 'Cubará' },
  { codigoDepartamento: '15', codigo: '15224', nombre: 'Cucaita' },
  { codigoDepartamento: '15', codigo: '15226', nombre: 'Cuítiva' },
  { codigoDepartamento: '15', codigo: '15232', nombre: 'Chíquiza' },
  { codigoDepartamento: '15', codigo: '15236', nombre: 'Chivor' },
  { codigoDepartamento: '15', codigo: '15238', nombre: 'Duitama' },
  { codigoDepartamento: '15', codigo: '15244', nombre: 'El Cocuy' },
  { codigoDepartamento: '15', codigo: '15248', nombre: 'El Espino' },
  { codigoDepartamento: '15', codigo: '15272', nombre: 'Firavitoba' },
  { codigoDepartamento: '15', codigo: '15276', nombre: 'Floresta' },
  { codigoDepartamento: '15', codigo: '15293', nombre: 'Gachantivá' },
  { codigoDepartamento: '15', codigo: '15296', nombre: 'Gámeza' },
  { codigoDepartamento: '15', codigo: '15299', nombre: 'Garagoa' },
  { codigoDepartamento: '15', codigo: '15317', nombre: 'Guacamayas' },
  { codigoDepartamento: '15', codigo: '15322', nombre: 'Guateque' },
  { codigoDepartamento: '15', codigo: '15325', nombre: 'Guayatá' },
  { codigoDepartamento: '15', codigo: '15332', nombre: 'Güicán de la Sierra' },
  { codigoDepartamento: '15', codigo: '15362', nombre: 'Iza' },
  { codigoDepartamento: '15', codigo: '15367', nombre: 'Jenesano' },
  { codigoDepartamento: '15', codigo: '15368', nombre: 'Jericó' },
  { codigoDepartamento: '15', codigo: '15377', nombre: 'Labranzagrande' },
  { codigoDepartamento: '15', codigo: '15380', nombre: 'La Capilla' },
  { codigoDepartamento: '15', codigo: '15401', nombre: 'La Victoria' },
  { codigoDepartamento: '15', codigo: '15403', nombre: 'La Uvita' },
  { codigoDepartamento: '15', codigo: '15407', nombre: 'Villa de Leyva' },
  { codigoDepartamento: '15', codigo: '15425', nombre: 'Macanal' },
  { codigoDepartamento: '15', codigo: '15442', nombre: 'Maripí' },
  { codigoDepartamento: '15', codigo: '15455', nombre: 'Miraflores' },
  { codigoDepartamento: '15', codigo: '15464', nombre: 'Mongua' },
  { codigoDepartamento: '15', codigo: '15466', nombre: 'Monguí' },
  { codigoDepartamento: '15', codigo: '15469', nombre: 'Moniquirá' },
  { codigoDepartamento: '15', codigo: '15476', nombre: 'Motavita' },
  { codigoDepartamento: '15', codigo: '15480', nombre: 'Muzo' },
  { codigoDepartamento: '15', codigo: '15491', nombre: 'Nobsa' },
  { codigoDepartamento: '15', codigo: '15494', nombre: 'Nuevo Colón' },
  { codigoDepartamento: '15', codigo: '15500', nombre: 'Oicatá' },
  { codigoDepartamento: '15', codigo: '15507', nombre: 'Otanche' },
  { codigoDepartamento: '15', codigo: '15511', nombre: 'Pachavita' },
  { codigoDepartamento: '15', codigo: '15514', nombre: 'Páez' },
  { codigoDepartamento: '15', codigo: '15516', nombre: 'Paipa' },
  { codigoDepartamento: '15', codigo: '15518', nombre: 'Pajarito' },
  { codigoDepartamento: '15', codigo: '15522', nombre: 'Panqueba' },
  { codigoDepartamento: '15', codigo: '15531', nombre: 'Pauna' },
  { codigoDepartamento: '15', codigo: '15533', nombre: 'Paya' },
  { codigoDepartamento: '15', codigo: '15537', nombre: 'Paz de Río' },
  { codigoDepartamento: '15', codigo: '15542', nombre: 'Pesca' },
  { codigoDepartamento: '15', codigo: '15550', nombre: 'Pisba' },
  { codigoDepartamento: '15', codigo: '15572', nombre: 'Puerto Boyacá' },
  { codigoDepartamento: '15', codigo: '15580', nombre: 'Quípama' },
  { codigoDepartamento: '15', codigo: '15599', nombre: 'Ramiriquí' },
  { codigoDepartamento: '15', codigo: '15600', nombre: 'Ráquira' },
  { codigoDepartamento: '15', codigo: '15621', nombre: 'Rondón' },
  { codigoDepartamento: '15', codigo: '15632', nombre: 'Saboyá' },
  { codigoDepartamento: '15', codigo: '15638', nombre: 'Sáchica' },
  { codigoDepartamento: '15', codigo: '15646', nombre: 'Samacá' },
  { codigoDepartamento: '15', codigo: '15660', nombre: 'San Eduardo' },
  { codigoDepartamento: '15', codigo: '15664', nombre: 'San José de Pare' },
  { codigoDepartamento: '15', codigo: '15667', nombre: 'San Luis de Gaceno' },
  { codigoDepartamento: '15', codigo: '15673', nombre: 'San Mateo' },
  { codigoDepartamento: '15', codigo: '15676', nombre: 'San Miguel de Sema' },
  { codigoDepartamento: '15', codigo: '15681', nombre: 'San Pablo de Borbur' },
  { codigoDepartamento: '15', codigo: '15686', nombre: 'Santana' },
  { codigoDepartamento: '15', codigo: '15690', nombre: 'Santa María' },
  { codigoDepartamento: '15', codigo: '15693', nombre: 'Santa Rosa de Viterbo' },
  { codigoDepartamento: '15', codigo: '15696', nombre: 'Santa Sofía' },
  { codigoDepartamento: '15', codigo: '15720', nombre: 'Sativanorte' },
  { codigoDepartamento: '15', codigo: '15723', nombre: 'Sativasur' },
  { codigoDepartamento: '15', codigo: '15740', nombre: 'Siachoque' },
  { codigoDepartamento: '15', codigo: '15753', nombre: 'Soatá' },
  { codigoDepartamento: '15', codigo: '15755', nombre: 'Socotá' },
  { codigoDepartamento: '15', codigo: '15757', nombre: 'Socha' },
  { codigoDepartamento: '15', codigo: '15759', nombre: 'Sogamoso' },
  { codigoDepartamento: '15', codigo: '15761', nombre: 'Somondoco' },
  { codigoDepartamento: '15', codigo: '15762', nombre: 'Sora' },
  { codigoDepartamento: '15', codigo: '15763', nombre: 'Sotaquirá' },
  { codigoDepartamento: '15', codigo: '15764', nombre: 'Soracá' },
  { codigoDepartamento: '15', codigo: '15774', nombre: 'Susacón' },
  { codigoDepartamento: '15', codigo: '15776', nombre: 'Sutamarchán' },
  { codigoDepartamento: '15', codigo: '15778', nombre: 'Sutatenza' },
  { codigoDepartamento: '15', codigo: '15790', nombre: 'Tasco' },
  { codigoDepartamento: '15', codigo: '15798', nombre: 'Tenza' },
  { codigoDepartamento: '15', codigo: '15804', nombre: 'Tibaná' },
  { codigoDepartamento: '15', codigo: '15806', nombre: 'Tibasosa' },
  { codigoDepartamento: '15', codigo: '15808', nombre: 'Tinjacá' },
  { codigoDepartamento: '15', codigo: '15810', nombre: 'Tipacoque' },
  { codigoDepartamento: '15', codigo: '15814', nombre: 'Toca' },
  { codigoDepartamento: '15', codigo: '15816', nombre: 'Togüí' },
  { codigoDepartamento: '15', codigo: '15820', nombre: 'Tópaga' },
  { codigoDepartamento: '15', codigo: '15822', nombre: 'Tota' },
  { codigoDepartamento: '15', codigo: '15832', nombre: 'Tununguá' },
  { codigoDepartamento: '15', codigo: '15835', nombre: 'Turmequé' },
  { codigoDepartamento: '15', codigo: '15837', nombre: 'Tuta' },
  { codigoDepartamento: '15', codigo: '15839', nombre: 'Tutazá' },
  { codigoDepartamento: '15', codigo: '15842', nombre: 'Úmbita' },
  { codigoDepartamento: '15', codigo: '15861', nombre: 'Ventaquemada' },
  { codigoDepartamento: '15', codigo: '15879', nombre: 'Viracachá' },
  { codigoDepartamento: '15', codigo: '15897', nombre: 'Zetaquira' },
  { codigoDepartamento: '17', codigo: '17001', nombre: 'Manizales' },
  { codigoDepartamento: '17', codigo: '17013', nombre: 'Aguadas' },
  { codigoDepartamento: '17', codigo: '17042', nombre: 'Anserma' },
  { codigoDepartamento: '17', codigo: '17050', nombre: 'Aranzazu' },
  { codigoDepartamento: '17', codigo: '17088', nombre: 'Belalcázar' },
  { codigoDepartamento: '17', codigo: '17174', nombre: 'Chinchiná' },
  { codigoDepartamento: '17', codigo: '17272', nombre: 'Filadelfia' },
  { codigoDepartamento: '17', codigo: '17380', nombre: 'La Dorada' },
  { codigoDepartamento: '17', codigo: '17388', nombre: 'La Merced' },
  { codigoDepartamento: '17', codigo: '17433', nombre: 'Manzanares' },
  { codigoDepartamento: '17', codigo: '17442', nombre: 'Marmato' },
  { codigoDepartamento: '17', codigo: '17444', nombre: 'Marquetalia' },
  { codigoDepartamento: '17', codigo: '17446', nombre: 'Marulanda' },
  { codigoDepartamento: '17', codigo: '17486', nombre: 'Neira' },
  { codigoDepartamento: '17', codigo: '17495', nombre: 'Norcasia' },
  { codigoDepartamento: '17', codigo: '17513', nombre: 'Pácora' },
  { codigoDepartamento: '17', codigo: '17524', nombre: 'Palestina' },
  { codigoDepartamento: '17', codigo: '17541', nombre: 'Pensilvania' },
  { codigoDepartamento: '17', codigo: '17614', nombre: 'Riosucio' },
  { codigoDepartamento: '17', codigo: '17616', nombre: 'Risaralda' },
  { codigoDepartamento: '17', codigo: '17653', nombre: 'Salamina' },
  { codigoDepartamento: '17', codigo: '17662', nombre: 'Samaná' },
  { codigoDepartamento: '17', codigo: '17665', nombre: 'San José' },
  { codigoDepartamento: '17', codigo: '17777', nombre: 'Supía' },
  { codigoDepartamento: '17', codigo: '17867', nombre: 'Victoria' },
  { codigoDepartamento: '17', codigo: '17873', nombre: 'Villamaría' },
  { codigoDepartamento: '17', codigo: '17877', nombre: 'Viterbo' },
  { codigoDepartamento: '18', codigo: '18001', nombre: 'Florencia' },
  { codigoDepartamento: '18', codigo: '18029', nombre: 'Albania' },
  { codigoDepartamento: '18', codigo: '18094', nombre: 'Belén de los Andaquíes' },
  { codigoDepartamento: '18', codigo: '18150', nombre: 'Cartagena del Chairá' },
  { codigoDepartamento: '18', codigo: '18205', nombre: 'Curillo' },
  { codigoDepartamento: '18', codigo: '18247', nombre: 'El Doncello' },
  { codigoDepartamento: '18', codigo: '18256', nombre: 'El Paujíl' },
  { codigoDepartamento: '18', codigo: '18410', nombre: 'La Montañita' },
  { codigoDepartamento: '18', codigo: '18460', nombre: 'Milán' },
  { codigoDepartamento: '18', codigo: '18479', nombre: 'Morelia' },
  { codigoDepartamento: '18', codigo: '18592', nombre: 'Puerto Rico' },
  { codigoDepartamento: '18', codigo: '18610', nombre: 'San José del Fragua' },
  { codigoDepartamento: '18', codigo: '18753', nombre: 'San Vicente del Caguán' },
  { codigoDepartamento: '18', codigo: '18756', nombre: 'Solano' },
  { codigoDepartamento: '18', codigo: '18785', nombre: 'Solita' },
  { codigoDepartamento: '18', codigo: '18860', nombre: 'Valparaíso' },
  { codigoDepartamento: '19', codigo: '19001', nombre: 'Popayán' },
  { codigoDepartamento: '19', codigo: '19022', nombre: 'Almaguer' },
  { codigoDepartamento: '19', codigo: '19050', nombre: 'Argelia' },
  { codigoDepartamento: '19', codigo: '19075', nombre: 'Balboa' },
  { codigoDepartamento: '19', codigo: '19100', nombre: 'Bolívar' },
  { codigoDepartamento: '19', codigo: '19110', nombre: 'Buenos Aires' },
  { codigoDepartamento: '19', codigo: '19130', nombre: 'Cajibío' },
  { codigoDepartamento: '19', codigo: '19137', nombre: 'Caldono' },
  { codigoDepartamento: '19', codigo: '19142', nombre: 'Caloto' },
  { codigoDepartamento: '19', codigo: '19212', nombre: 'Corinto' },
  { codigoDepartamento: '19', codigo: '19256', nombre: 'El Tambo' },
  { codigoDepartamento: '19', codigo: '19290', nombre: 'Florencia' },
  { codigoDepartamento: '19', codigo: '19300', nombre: 'Guachené' },
  { codigoDepartamento: '19', codigo: '19318', nombre: 'Guapi' },
  { codigoDepartamento: '19', codigo: '19355', nombre: 'Inzá' },
  { codigoDepartamento: '19', codigo: '19364', nombre: 'Jambaló' },
  { codigoDepartamento: '19', codigo: '19392', nombre: 'La Sierra' },
  { codigoDepartamento: '19', codigo: '19397', nombre: 'La Vega' },
  { codigoDepartamento: '19', codigo: '19418', nombre: 'López de Micay' },
  { codigoDepartamento: '19', codigo: '19450', nombre: 'Mercaderes' },
  { codigoDepartamento: '19', codigo: '19455', nombre: 'Miranda' },
  { codigoDepartamento: '19', codigo: '19473', nombre: 'Morales' },
  { codigoDepartamento: '19', codigo: '19513', nombre: 'Padilla' },
  { codigoDepartamento: '19', codigo: '19517', nombre: 'Páez' },
  { codigoDepartamento: '19', codigo: '19532', nombre: 'Patía' },
  { codigoDepartamento: '19', codigo: '19533', nombre: 'Piamonte' },
  { codigoDepartamento: '19', codigo: '19548', nombre: 'Piendamó - Tunía' },
  { codigoDepartamento: '19', codigo: '19573', nombre: 'Puerto Tejada' },
  { codigoDepartamento: '19', codigo: '19585', nombre: 'Puracé' },
  { codigoDepartamento: '19', codigo: '19622', nombre: 'Rosas' },
  { codigoDepartamento: '19', codigo: '19693', nombre: 'San Sebastián' },
  { codigoDepartamento: '19', codigo: '19698', nombre: 'Santander de Quilichao' },
  { codigoDepartamento: '19', codigo: '19701', nombre: 'Santa Rosa' },
  { codigoDepartamento: '19', codigo: '19743', nombre: 'Silvia' },
  { codigoDepartamento: '19', codigo: '19760', nombre: 'Sotará - Paispamba' },
  { codigoDepartamento: '19', codigo: '19780', nombre: 'Suárez' },
  { codigoDepartamento: '19', codigo: '19785', nombre: 'Sucre' },
  { codigoDepartamento: '19', codigo: '19807', nombre: 'Timbío' },
  { codigoDepartamento: '19', codigo: '19809', nombre: 'Timbiquí' },
  { codigoDepartamento: '19', codigo: '19821', nombre: 'Toribío' },
  { codigoDepartamento: '19', codigo: '19824', nombre: 'Totoró' },
  { codigoDepartamento: '19', codigo: '19845', nombre: 'Villa Rica' },
  { codigoDepartamento: '20', codigo: '20001', nombre: 'Valledupar' },
  { codigoDepartamento: '20', codigo: '20011', nombre: 'Aguachica' },
  { codigoDepartamento: '20', codigo: '20013', nombre: 'Agustín Codazzi' },
  { codigoDepartamento: '20', codigo: '20032', nombre: 'Astrea' },
  { codigoDepartamento: '20', codigo: '20045', nombre: 'Becerril' },
  { codigoDepartamento: '20', codigo: '20060', nombre: 'Bosconia' },
  { codigoDepartamento: '20', codigo: '20175', nombre: 'Chimichagua' },
  { codigoDepartamento: '20', codigo: '20178', nombre: 'Chiriguaná' },
  { codigoDepartamento: '20', codigo: '20228', nombre: 'Curumaní' },
  { codigoDepartamento: '20', codigo: '20238', nombre: 'El Copey' },
  { codigoDepartamento: '20', codigo: '20250', nombre: 'El Paso' },
  { codigoDepartamento: '20', codigo: '20295', nombre: 'Gamarra' },
  { codigoDepartamento: '20', codigo: '20310', nombre: 'González' },
  { codigoDepartamento: '20', codigo: '20383', nombre: 'La Gloria' },
  { codigoDepartamento: '20', codigo: '20400', nombre: 'La Jagua de Ibirico' },
  { codigoDepartamento: '20', codigo: '20443', nombre: 'Manaure Balcón del Cesar' },
  { codigoDepartamento: '20', codigo: '20517', nombre: 'Pailitas' },
  { codigoDepartamento: '20', codigo: '20550', nombre: 'Pelaya' },
  { codigoDepartamento: '20', codigo: '20570', nombre: 'Pueblo Bello' },
  { codigoDepartamento: '20', codigo: '20614', nombre: 'Río de Oro' },
  { codigoDepartamento: '20', codigo: '20621', nombre: 'La Paz' },
  { codigoDepartamento: '20', codigo: '20710', nombre: 'San Alberto' },
  { codigoDepartamento: '20', codigo: '20750', nombre: 'San Diego' },
  { codigoDepartamento: '20', codigo: '20770', nombre: 'San Martín' },
  { codigoDepartamento: '20', codigo: '20787', nombre: 'Tamalameque' },
  { codigoDepartamento: '23', codigo: '23001', nombre: 'Montería' },
  { codigoDepartamento: '23', codigo: '23068', nombre: 'Ayapel' },
  { codigoDepartamento: '23', codigo: '23079', nombre: 'Buenavista' },
  { codigoDepartamento: '23', codigo: '23090', nombre: 'Canalete' },
  { codigoDepartamento: '23', codigo: '23162', nombre: 'Cereté' },
  { codigoDepartamento: '23', codigo: '23168', nombre: 'Chimá' },
  { codigoDepartamento: '23', codigo: '23182', nombre: 'Chinú' },
  { codigoDepartamento: '23', codigo: '23189', nombre: 'Ciénaga de Oro' },
  { codigoDepartamento: '23', codigo: '23300', nombre: 'Cotorra' },
  { codigoDepartamento: '23', codigo: '23350', nombre: 'La Apartada' },
  { codigoDepartamento: '23', codigo: '23417', nombre: 'Lorica' },
  { codigoDepartamento: '23', codigo: '23419', nombre: 'Los Córdobas' },
  { codigoDepartamento: '23', codigo: '23464', nombre: 'Momil' },
  { codigoDepartamento: '23', codigo: '23466', nombre: 'Montelíbano' },
  { codigoDepartamento: '23', codigo: '23500', nombre: 'Moñitos' },
  { codigoDepartamento: '23', codigo: '23555', nombre: 'Planeta Rica' },
  { codigoDepartamento: '23', codigo: '23570', nombre: 'Pueblo Nuevo' },
  { codigoDepartamento: '23', codigo: '23574', nombre: 'Puerto Escondido' },
  { codigoDepartamento: '23', codigo: '23580', nombre: 'Puerto Libertador' },
  { codigoDepartamento: '23', codigo: '23586', nombre: 'Purísima de la Concepción' },
  { codigoDepartamento: '23', codigo: '23660', nombre: 'Sahagún' },
  { codigoDepartamento: '23', codigo: '23670', nombre: 'San Andrés de Sotavento' },
  { codigoDepartamento: '23', codigo: '23672', nombre: 'San Antero' },
  { codigoDepartamento: '23', codigo: '23675', nombre: 'San Bernardo del Viento' },
  { codigoDepartamento: '23', codigo: '23678', nombre: 'San Carlos' },
  { codigoDepartamento: '23', codigo: '23682', nombre: 'San José de Uré' },
  { codigoDepartamento: '23', codigo: '23686', nombre: 'San Pelayo' },
  { codigoDepartamento: '23', codigo: '23807', nombre: 'Tierralta' },
  { codigoDepartamento: '23', codigo: '23815', nombre: 'Tuchín' },
  { codigoDepartamento: '23', codigo: '23855', nombre: 'Valencia' },
  { codigoDepartamento: '25', codigo: '25001', nombre: 'Agua de Dios' },
  { codigoDepartamento: '25', codigo: '25019', nombre: 'Albán' },
  { codigoDepartamento: '25', codigo: '25035', nombre: 'Anapoima' },
  { codigoDepartamento: '25', codigo: '25040', nombre: 'Anolaima' },
  { codigoDepartamento: '25', codigo: '25053', nombre: 'Arbeláez' },
  { codigoDepartamento: '25', codigo: '25086', nombre: 'Beltrán' },
  { codigoDepartamento: '25', codigo: '25095', nombre: 'Bituima' },
  { codigoDepartamento: '25', codigo: '25099', nombre: 'Bojacá' },
  { codigoDepartamento: '25', codigo: '25120', nombre: 'Cabrera' },
  { codigoDepartamento: '25', codigo: '25123', nombre: 'Cachipay' },
  { codigoDepartamento: '25', codigo: '25126', nombre: 'Cajicá' },
  { codigoDepartamento: '25', codigo: '25148', nombre: 'Caparrapí' },
  { codigoDepartamento: '25', codigo: '25151', nombre: 'Cáqueza' },
  { codigoDepartamento: '25', codigo: '25154', nombre: 'Carmen de Carupa' },
  { codigoDepartamento: '25', codigo: '25168', nombre: 'Chaguaní' },
  { codigoDepartamento: '25', codigo: '25175', nombre: 'Chía' },
  { codigoDepartamento: '25', codigo: '25178', nombre: 'Chipaque' },
  { codigoDepartamento: '25', codigo: '25181', nombre: 'Choachí' },
  { codigoDepartamento: '25', codigo: '25183', nombre: 'Chocontá' },
  { codigoDepartamento: '25', codigo: '25200', nombre: 'Cogua' },
  { codigoDepartamento: '25', codigo: '25214', nombre: 'Cota' },
  { codigoDepartamento: '25', codigo: '25224', nombre: 'Cucunubá' },
  { codigoDepartamento: '25', codigo: '25245', nombre: 'El Colegio' },
  { codigoDepartamento: '25', codigo: '25258', nombre: 'El Peñón' },
  { codigoDepartamento: '25', codigo: '25260', nombre: 'El Rosal' },
  { codigoDepartamento: '25', codigo: '25269', nombre: 'Facatativá' },
  { codigoDepartamento: '25', codigo: '25279', nombre: 'Fómeque' },
  { codigoDepartamento: '25', codigo: '25281', nombre: 'Fosca' },
  { codigoDepartamento: '25', codigo: '25286', nombre: 'Funza' },
  { codigoDepartamento: '25', codigo: '25288', nombre: 'Fúquene' },
  { codigoDepartamento: '25', codigo: '25290', nombre: 'Fusagasugá' },
  { codigoDepartamento: '25', codigo: '25293', nombre: 'Gachalá' },
  { codigoDepartamento: '25', codigo: '25295', nombre: 'Gachancipá' },
  { codigoDepartamento: '25', codigo: '25297', nombre: 'Gachetá' },
  { codigoDepartamento: '25', codigo: '25299', nombre: 'Gama' },
  { codigoDepartamento: '25', codigo: '25307', nombre: 'Girardot' },
  { codigoDepartamento: '25', codigo: '25312', nombre: 'Granada' },
  { codigoDepartamento: '25', codigo: '25317', nombre: 'Guachetá' },
  { codigoDepartamento: '25', codigo: '25320', nombre: 'Guaduas' },
  { codigoDepartamento: '25', codigo: '25322', nombre: 'Guasca' },
  { codigoDepartamento: '25', codigo: '25324', nombre: 'Guataquí' },
  { codigoDepartamento: '25', codigo: '25326', nombre: 'Guatavita' },
  { codigoDepartamento: '25', codigo: '25328', nombre: 'Guayabal de Síquima' },
  { codigoDepartamento: '25', codigo: '25335', nombre: 'Guayabetal' },
  { codigoDepartamento: '25', codigo: '25339', nombre: 'Gutiérrez' },
  { codigoDepartamento: '25', codigo: '25368', nombre: 'Jerusalén' },
  { codigoDepartamento: '25', codigo: '25372', nombre: 'Junín' },
  { codigoDepartamento: '25', codigo: '25377', nombre: 'La Calera' },
  { codigoDepartamento: '25', codigo: '25386', nombre: 'La Mesa' },
  { codigoDepartamento: '25', codigo: '25394', nombre: 'La Palma' },
  { codigoDepartamento: '25', codigo: '25398', nombre: 'La Peña' },
  { codigoDepartamento: '25', codigo: '25402', nombre: 'La Vega' },
  { codigoDepartamento: '25', codigo: '25407', nombre: 'Lenguazaque' },
  { codigoDepartamento: '25', codigo: '25426', nombre: 'Machetá' },
  { codigoDepartamento: '25', codigo: '25430', nombre: 'Madrid' },
  { codigoDepartamento: '25', codigo: '25436', nombre: 'Manta' },
  { codigoDepartamento: '25', codigo: '25438', nombre: 'Medina' },
  { codigoDepartamento: '25', codigo: '25473', nombre: 'Mosquera' },
  { codigoDepartamento: '25', codigo: '25483', nombre: 'Nariño' },
  { codigoDepartamento: '25', codigo: '25486', nombre: 'Nemocón' },
  { codigoDepartamento: '25', codigo: '25488', nombre: 'Nilo' },
  { codigoDepartamento: '25', codigo: '25489', nombre: 'Nimaima' },
  { codigoDepartamento: '25', codigo: '25491', nombre: 'Nocaima' },
  { codigoDepartamento: '25', codigo: '25506', nombre: 'Venecia' },
  { codigoDepartamento: '25', codigo: '25513', nombre: 'Pacho' },
  { codigoDepartamento: '25', codigo: '25518', nombre: 'Paime' },
  { codigoDepartamento: '25', codigo: '25524', nombre: 'Pandi' },
  { codigoDepartamento: '25', codigo: '25530', nombre: 'Paratebueno' },
  { codigoDepartamento: '25', codigo: '25535', nombre: 'Pasca' },
  { codigoDepartamento: '25', codigo: '25572', nombre: 'Puerto Salgar' },
  { codigoDepartamento: '25', codigo: '25580', nombre: 'Pulí' },
  { codigoDepartamento: '25', codigo: '25592', nombre: 'Quebradanegra' },
  { codigoDepartamento: '25', codigo: '25594', nombre: 'Quetame' },
  { codigoDepartamento: '25', codigo: '25596', nombre: 'Quipile' },
  { codigoDepartamento: '25', codigo: '25599', nombre: 'Apulo' },
  { codigoDepartamento: '25', codigo: '25612', nombre: 'Ricaurte' },
  { codigoDepartamento: '25', codigo: '25645', nombre: 'San Antonio del Tequendama' },
  { codigoDepartamento: '25', codigo: '25649', nombre: 'San Bernardo' },
  { codigoDepartamento: '25', codigo: '25653', nombre: 'San Cayetano' },
  { codigoDepartamento: '25', codigo: '25658', nombre: 'San Francisco' },
  { codigoDepartamento: '25', codigo: '25662', nombre: 'San Juan de Rioseco' },
  { codigoDepartamento: '25', codigo: '25718', nombre: 'Sasaima' },
  { codigoDepartamento: '25', codigo: '25736', nombre: 'Sesquilé' },
  { codigoDepartamento: '25', codigo: '25740', nombre: 'Sibaté' },
  { codigoDepartamento: '25', codigo: '25743', nombre: 'Silvania' },
  { codigoDepartamento: '25', codigo: '25745', nombre: 'Simijaca' },
  { codigoDepartamento: '25', codigo: '25754', nombre: 'Soacha' },
  { codigoDepartamento: '25', codigo: '25758', nombre: 'Sopó' },
  { codigoDepartamento: '25', codigo: '25769', nombre: 'Subachoque' },
  { codigoDepartamento: '25', codigo: '25772', nombre: 'Suesca' },
  { codigoDepartamento: '25', codigo: '25777', nombre: 'Supatá' },
  { codigoDepartamento: '25', codigo: '25779', nombre: 'Susa' },
  { codigoDepartamento: '25', codigo: '25781', nombre: 'Sutatausa' },
  { codigoDepartamento: '25', codigo: '25785', nombre: 'Tabio' },
  { codigoDepartamento: '25', codigo: '25793', nombre: 'Tausa' },
  { codigoDepartamento: '25', codigo: '25797', nombre: 'Tena' },
  { codigoDepartamento: '25', codigo: '25799', nombre: 'Tenjo' },
  { codigoDepartamento: '25', codigo: '25805', nombre: 'Tibacuy' },
  { codigoDepartamento: '25', codigo: '25807', nombre: 'Tibirita' },
  { codigoDepartamento: '25', codigo: '25815', nombre: 'Tocaima' },
  { codigoDepartamento: '25', codigo: '25817', nombre: 'Tocancipá' },
  { codigoDepartamento: '25', codigo: '25823', nombre: 'Topaipí' },
  { codigoDepartamento: '25', codigo: '25839', nombre: 'Ubalá' },
  { codigoDepartamento: '25', codigo: '25841', nombre: 'Ubaque' },
  { codigoDepartamento: '25', codigo: '25843', nombre: 'Villa de San Diego de Ubaté' },
  { codigoDepartamento: '25', codigo: '25845', nombre: 'Une' },
  { codigoDepartamento: '25', codigo: '25851', nombre: 'Útica' },
  { codigoDepartamento: '25', codigo: '25862', nombre: 'Vergara' },
  { codigoDepartamento: '25', codigo: '25867', nombre: 'Vianí' },
  { codigoDepartamento: '25', codigo: '25871', nombre: 'Villagómez' },
  { codigoDepartamento: '25', codigo: '25873', nombre: 'Villapinzón' },
  { codigoDepartamento: '25', codigo: '25875', nombre: 'Villeta' },
  { codigoDepartamento: '25', codigo: '25878', nombre: 'Viotá' },
  { codigoDepartamento: '25', codigo: '25885', nombre: 'Yacopí' },
  { codigoDepartamento: '25', codigo: '25898', nombre: 'Zipacón' },
  { codigoDepartamento: '25', codigo: '25899', nombre: 'Zipaquirá' },
  { codigoDepartamento: '27', codigo: '27001', nombre: 'Quibdó' },
  { codigoDepartamento: '27', codigo: '27006', nombre: 'Acandí' },
  { codigoDepartamento: '27', codigo: '27025', nombre: 'Alto Baudó' },
  { codigoDepartamento: '27', codigo: '27050', nombre: 'Atrato' },
  { codigoDepartamento: '27', codigo: '27073', nombre: 'Bagadó' },
  { codigoDepartamento: '27', codigo: '27075', nombre: 'Bahía Solano' },
  { codigoDepartamento: '27', codigo: '27077', nombre: 'Bajo Baudó' },
  { codigoDepartamento: '27', codigo: '27099', nombre: 'Bojayá' },
  { codigoDepartamento: '27', codigo: '27135', nombre: 'El Cantón del San Pablo' },
  { codigoDepartamento: '27', codigo: '27150', nombre: 'Carmen del Darién' },
  { codigoDepartamento: '27', codigo: '27160', nombre: 'Cértegui' },
  { codigoDepartamento: '27', codigo: '27205', nombre: 'Condoto' },
  { codigoDepartamento: '27', codigo: '27245', nombre: 'El Carmen de Atrato' },
  { codigoDepartamento: '27', codigo: '27250', nombre: 'El Litoral del San Juan' },
  { codigoDepartamento: '27', codigo: '27361', nombre: 'Istmina' },
  { codigoDepartamento: '27', codigo: '27372', nombre: 'Juradó' },
  { codigoDepartamento: '27', codigo: '27413', nombre: 'Lloró' },
  { codigoDepartamento: '27', codigo: '27425', nombre: 'Medio Atrato' },
  { codigoDepartamento: '27', codigo: '27430', nombre: 'Medio Baudó' },
  { codigoDepartamento: '27', codigo: '27450', nombre: 'Medio San Juan' },
  { codigoDepartamento: '27', codigo: '27491', nombre: 'Nóvita' },
  { codigoDepartamento: '27', codigo: '27493', nombre: 'Nuevo Belén de Bajirá' },
  { codigoDepartamento: '27', codigo: '27495', nombre: 'Nuquí' },
  { codigoDepartamento: '27', codigo: '27580', nombre: 'Río Iró' },
  { codigoDepartamento: '27', codigo: '27600', nombre: 'Río Quito' },
  { codigoDepartamento: '27', codigo: '27615', nombre: 'Riosucio' },
  { codigoDepartamento: '27', codigo: '27660', nombre: 'San José del Palmar' },
  { codigoDepartamento: '27', codigo: '27745', nombre: 'Sipí' },
  { codigoDepartamento: '27', codigo: '27787', nombre: 'Tadó' },
  { codigoDepartamento: '27', codigo: '27800', nombre: 'Unguía' },
  { codigoDepartamento: '27', codigo: '27810', nombre: 'Unión Panamericana' },
  { codigoDepartamento: '41', codigo: '41001', nombre: 'Neiva' },
  { codigoDepartamento: '41', codigo: '41006', nombre: 'Acevedo' },
  { codigoDepartamento: '41', codigo: '41013', nombre: 'Agrado' },
  { codigoDepartamento: '41', codigo: '41016', nombre: 'Aipe' },
  { codigoDepartamento: '41', codigo: '41020', nombre: 'Algeciras' },
  { codigoDepartamento: '41', codigo: '41026', nombre: 'Altamira' },
  { codigoDepartamento: '41', codigo: '41078', nombre: 'Baraya' },
  { codigoDepartamento: '41', codigo: '41132', nombre: 'Campoalegre' },
  { codigoDepartamento: '41', codigo: '41206', nombre: 'Colombia' },
  { codigoDepartamento: '41', codigo: '41244', nombre: 'Elías' },
  { codigoDepartamento: '41', codigo: '41298', nombre: 'Garzón' },
  { codigoDepartamento: '41', codigo: '41306', nombre: 'Gigante' },
  { codigoDepartamento: '41', codigo: '41319', nombre: 'Guadalupe' },
  { codigoDepartamento: '41', codigo: '41349', nombre: 'Hobo' },
  { codigoDepartamento: '41', codigo: '41357', nombre: 'Íquira' },
  { codigoDepartamento: '41', codigo: '41359', nombre: 'Isnos' },
  { codigoDepartamento: '41', codigo: '41378', nombre: 'La Argentina' },
  { codigoDepartamento: '41', codigo: '41396', nombre: 'La Plata' },
  { codigoDepartamento: '41', codigo: '41483', nombre: 'Nátaga' },
  { codigoDepartamento: '41', codigo: '41503', nombre: 'Oporapa' },
  { codigoDepartamento: '41', codigo: '41518', nombre: 'Paicol' },
  { codigoDepartamento: '41', codigo: '41524', nombre: 'Palermo' },
  { codigoDepartamento: '41', codigo: '41530', nombre: 'Palestina' },
  { codigoDepartamento: '41', codigo: '41548', nombre: 'Pital' },
  { codigoDepartamento: '41', codigo: '41551', nombre: 'Pitalito' },
  { codigoDepartamento: '41', codigo: '41615', nombre: 'Rivera' },
  { codigoDepartamento: '41', codigo: '41660', nombre: 'Saladoblanco' },
  { codigoDepartamento: '41', codigo: '41668', nombre: 'San Agustín' },
  { codigoDepartamento: '41', codigo: '41676', nombre: 'Santa María' },
  { codigoDepartamento: '41', codigo: '41770', nombre: 'Suaza' },
  { codigoDepartamento: '41', codigo: '41791', nombre: 'Tarqui' },
  { codigoDepartamento: '41', codigo: '41797', nombre: 'Tesalia' },
  { codigoDepartamento: '41', codigo: '41799', nombre: 'Tello' },
  { codigoDepartamento: '41', codigo: '41801', nombre: 'Teruel' },
  { codigoDepartamento: '41', codigo: '41807', nombre: 'Timaná' },
  { codigoDepartamento: '41', codigo: '41872', nombre: 'Villavieja' },
  { codigoDepartamento: '41', codigo: '41885', nombre: 'Yaguará' },
  { codigoDepartamento: '44', codigo: '44001', nombre: 'Riohacha' },
  { codigoDepartamento: '44', codigo: '44035', nombre: 'Albania' },
  { codigoDepartamento: '44', codigo: '44078', nombre: 'Barrancas' },
  { codigoDepartamento: '44', codigo: '44090', nombre: 'Dibulla' },
  { codigoDepartamento: '44', codigo: '44098', nombre: 'Distracción' },
  { codigoDepartamento: '44', codigo: '44110', nombre: 'El Molino' },
  { codigoDepartamento: '44', codigo: '44279', nombre: 'Fonseca' },
  { codigoDepartamento: '44', codigo: '44378', nombre: 'Hatonuevo' },
  { codigoDepartamento: '44', codigo: '44420', nombre: 'La Jagua del Pilar' },
  { codigoDepartamento: '44', codigo: '44430', nombre: 'Maicao' },
  { codigoDepartamento: '44', codigo: '44560', nombre: 'Manaure' },
  { codigoDepartamento: '44', codigo: '44650', nombre: 'San Juan del Cesar' },
  { codigoDepartamento: '44', codigo: '44847', nombre: 'Uribia' },
  { codigoDepartamento: '44', codigo: '44855', nombre: 'Urumita' },
  { codigoDepartamento: '44', codigo: '44874', nombre: 'Villanueva' },
  { codigoDepartamento: '47', codigo: '47001', nombre: 'Santa Marta' },
  { codigoDepartamento: '47', codigo: '47030', nombre: 'Algarrobo' },
  { codigoDepartamento: '47', codigo: '47053', nombre: 'Aracataca' },
  { codigoDepartamento: '47', codigo: '47058', nombre: 'Ariguaní' },
  { codigoDepartamento: '47', codigo: '47161', nombre: 'Cerro de San Antonio' },
  { codigoDepartamento: '47', codigo: '47170', nombre: 'Chivolo' },
  { codigoDepartamento: '47', codigo: '47189', nombre: 'Ciénaga' },
  { codigoDepartamento: '47', codigo: '47205', nombre: 'Concordia' },
  { codigoDepartamento: '47', codigo: '47245', nombre: 'El Banco' },
  { codigoDepartamento: '47', codigo: '47258', nombre: 'El Piñón' },
  { codigoDepartamento: '47', codigo: '47268', nombre: 'El Retén' },
  { codigoDepartamento: '47', codigo: '47288', nombre: 'Fundación' },
  { codigoDepartamento: '47', codigo: '47318', nombre: 'Guamal' },
  { codigoDepartamento: '47', codigo: '47460', nombre: 'Nueva Granada' },
  { codigoDepartamento: '47', codigo: '47541', nombre: 'Pedraza' },
  { codigoDepartamento: '47', codigo: '47545', nombre: 'Pijiño del Carmen' },
  { codigoDepartamento: '47', codigo: '47551', nombre: 'Pivijay' },
  { codigoDepartamento: '47', codigo: '47555', nombre: 'Plato' },
  { codigoDepartamento: '47', codigo: '47570', nombre: 'Puebloviejo' },
  { codigoDepartamento: '47', codigo: '47605', nombre: 'Remolino' },
  { codigoDepartamento: '47', codigo: '47660', nombre: 'Sabanas de San Ángel' },
  { codigoDepartamento: '47', codigo: '47675', nombre: 'Salamina' },
  { codigoDepartamento: '47', codigo: '47692', nombre: 'San Sebastián de Buenavista' },
  { codigoDepartamento: '47', codigo: '47703', nombre: 'San Zenón' },
  { codigoDepartamento: '47', codigo: '47707', nombre: 'Santa Ana' },
  { codigoDepartamento: '47', codigo: '47720', nombre: 'Santa Bárbara de Pinto' },
  { codigoDepartamento: '47', codigo: '47745', nombre: 'Sitionuevo' },
  { codigoDepartamento: '47', codigo: '47798', nombre: 'Tenerife' },
  { codigoDepartamento: '47', codigo: '47960', nombre: 'Zapayán' },
  { codigoDepartamento: '47', codigo: '47980', nombre: 'Zona Bananera' },
  { codigoDepartamento: '50', codigo: '50001', nombre: 'Villavicencio' },
  { codigoDepartamento: '50', codigo: '50006', nombre: 'Acacías' },
  { codigoDepartamento: '50', codigo: '50110', nombre: 'Barranca de Upía' },
  { codigoDepartamento: '50', codigo: '50124', nombre: 'Cabuyaro' },
  { codigoDepartamento: '50', codigo: '50150', nombre: 'Castilla la Nueva' },
  { codigoDepartamento: '50', codigo: '50223', nombre: 'Cubarral' },
  { codigoDepartamento: '50', codigo: '50226', nombre: 'Cumaral' },
  { codigoDepartamento: '50', codigo: '50245', nombre: 'El Calvario' },
  { codigoDepartamento: '50', codigo: '50251', nombre: 'El Castillo' },
  { codigoDepartamento: '50', codigo: '50270', nombre: 'El Dorado' },
  { codigoDepartamento: '50', codigo: '50287', nombre: 'Fuente de Oro' },
  { codigoDepartamento: '50', codigo: '50313', nombre: 'Granada' },
  { codigoDepartamento: '50', codigo: '50318', nombre: 'Guamal' },
  { codigoDepartamento: '50', codigo: '50325', nombre: 'Mapiripán' },
  { codigoDepartamento: '50', codigo: '50330', nombre: 'Mesetas' },
  { codigoDepartamento: '50', codigo: '50350', nombre: 'La Macarena' },
  { codigoDepartamento: '50', codigo: '50370', nombre: 'Uribe' },
  { codigoDepartamento: '50', codigo: '50400', nombre: 'Lejanías' },
  { codigoDepartamento: '50', codigo: '50450', nombre: 'Puerto Concordia' },
  { codigoDepartamento: '50', codigo: '50568', nombre: 'Puerto Gaitán' },
  { codigoDepartamento: '50', codigo: '50573', nombre: 'Puerto López' },
  { codigoDepartamento: '50', codigo: '50577', nombre: 'Puerto Lleras' },
  { codigoDepartamento: '50', codigo: '50590', nombre: 'Puerto Rico' },
  { codigoDepartamento: '50', codigo: '50606', nombre: 'Restrepo' },
  { codigoDepartamento: '50', codigo: '50680', nombre: 'San Carlos de Guaroa' },
  { codigoDepartamento: '50', codigo: '50683', nombre: 'San Juan de Arama' },
  { codigoDepartamento: '50', codigo: '50686', nombre: 'San Juanito' },
  { codigoDepartamento: '50', codigo: '50689', nombre: 'San Martín' },
  { codigoDepartamento: '50', codigo: '50711', nombre: 'Vistahermosa' },
  { codigoDepartamento: '52', codigo: '52001', nombre: 'Pasto' },
  { codigoDepartamento: '52', codigo: '52019', nombre: 'Albán' },
  { codigoDepartamento: '52', codigo: '52022', nombre: 'Aldana' },
  { codigoDepartamento: '52', codigo: '52036', nombre: 'Ancuya' },
  { codigoDepartamento: '52', codigo: '52051', nombre: 'Arboleda' },
  { codigoDepartamento: '52', codigo: '52079', nombre: 'Barbacoas' },
  { codigoDepartamento: '52', codigo: '52083', nombre: 'Belén' },
  { codigoDepartamento: '52', codigo: '52110', nombre: 'Buesaco' },
  { codigoDepartamento: '52', codigo: '52203', nombre: 'Colón' },
  { codigoDepartamento: '52', codigo: '52207', nombre: 'Consacá' },
  { codigoDepartamento: '52', codigo: '52210', nombre: 'Contadero' },
  { codigoDepartamento: '52', codigo: '52215', nombre: 'Córdoba' },
  { codigoDepartamento: '52', codigo: '52224', nombre: 'Cuaspud Carlosama' },
  { codigoDepartamento: '52', codigo: '52227', nombre: 'Cumbal' },
  { codigoDepartamento: '52', codigo: '52233', nombre: 'Cumbitara' },
  { codigoDepartamento: '52', codigo: '52240', nombre: 'Chachagüí' },
  { codigoDepartamento: '52', codigo: '52250', nombre: 'El Charco' },
  { codigoDepartamento: '52', codigo: '52254', nombre: 'El Peñol' },
  { codigoDepartamento: '52', codigo: '52256', nombre: 'El Rosario' },
  { codigoDepartamento: '52', codigo: '52258', nombre: 'El Tablón de Gómez' },
  { codigoDepartamento: '52', codigo: '52260', nombre: 'El Tambo' },
  { codigoDepartamento: '52', codigo: '52287', nombre: 'Funes' },
  { codigoDepartamento: '52', codigo: '52317', nombre: 'Guachucal' },
  { codigoDepartamento: '52', codigo: '52320', nombre: 'Guaitarilla' },
  { codigoDepartamento: '52', codigo: '52323', nombre: 'Gualmatán' },
  { codigoDepartamento: '52', codigo: '52352', nombre: 'Iles' },
  { codigoDepartamento: '52', codigo: '52354', nombre: 'Imués' },
  { codigoDepartamento: '52', codigo: '52356', nombre: 'Ipiales' },
  { codigoDepartamento: '52', codigo: '52378', nombre: 'La Cruz' },
  { codigoDepartamento: '52', codigo: '52381', nombre: 'La Florida' },
  { codigoDepartamento: '52', codigo: '52385', nombre: 'La Llanada' },
  { codigoDepartamento: '52', codigo: '52390', nombre: 'La Tola' },
  { codigoDepartamento: '52', codigo: '52399', nombre: 'La Unión' },
  { codigoDepartamento: '52', codigo: '52405', nombre: 'Leiva' },
  { codigoDepartamento: '52', codigo: '52411', nombre: 'Linares' },
  { codigoDepartamento: '52', codigo: '52418', nombre: 'Los Andes' },
  { codigoDepartamento: '52', codigo: '52427', nombre: 'Magüí' },
  { codigoDepartamento: '52', codigo: '52435', nombre: 'Mallama' },
  { codigoDepartamento: '52', codigo: '52473', nombre: 'Mosquera' },
  { codigoDepartamento: '52', codigo: '52480', nombre: 'Nariño' },
  { codigoDepartamento: '52', codigo: '52490', nombre: 'Olaya Herrera' },
  { codigoDepartamento: '52', codigo: '52506', nombre: 'Ospina' },
  { codigoDepartamento: '52', codigo: '52520', nombre: 'Francisco Pizarro' },
  { codigoDepartamento: '52', codigo: '52540', nombre: 'Policarpa' },
  { codigoDepartamento: '52', codigo: '52560', nombre: 'Potosí' },
  { codigoDepartamento: '52', codigo: '52565', nombre: 'Providencia' },
  { codigoDepartamento: '52', codigo: '52573', nombre: 'Puerres' },
  { codigoDepartamento: '52', codigo: '52585', nombre: 'Pupiales' },
  { codigoDepartamento: '52', codigo: '52612', nombre: 'Ricaurte' },
  { codigoDepartamento: '52', codigo: '52621', nombre: 'Roberto Payán' },
  { codigoDepartamento: '52', codigo: '52678', nombre: 'Samaniego' },
  { codigoDepartamento: '52', codigo: '52683', nombre: 'Sandoná' },
  { codigoDepartamento: '52', codigo: '52685', nombre: 'San Bernardo' },
  { codigoDepartamento: '52', codigo: '52687', nombre: 'San Lorenzo' },
  { codigoDepartamento: '52', codigo: '52693', nombre: 'San Pablo' },
  { codigoDepartamento: '52', codigo: '52694', nombre: 'San Pedro de Cartago' },
  { codigoDepartamento: '52', codigo: '52696', nombre: 'Santa Bárbara' },
  { codigoDepartamento: '52', codigo: '52699', nombre: 'Santacruz' },
  { codigoDepartamento: '52', codigo: '52720', nombre: 'Sapuyes' },
  { codigoDepartamento: '52', codigo: '52786', nombre: 'Taminango' },
  { codigoDepartamento: '52', codigo: '52788', nombre: 'Tangua' },
  { codigoDepartamento: '52', codigo: '52835', nombre: 'San Andrés de Tumaco' },
  { codigoDepartamento: '52', codigo: '52838', nombre: 'Túquerres' },
  { codigoDepartamento: '52', codigo: '52885', nombre: 'Yacuanquer' },
  { codigoDepartamento: '54', codigo: '54001', nombre: 'San José de Cúcuta' },
  { codigoDepartamento: '54', codigo: '54003', nombre: 'Ábrego' },
  { codigoDepartamento: '54', codigo: '54051', nombre: 'Arboledas' },
  { codigoDepartamento: '54', codigo: '54099', nombre: 'Bochalema' },
  { codigoDepartamento: '54', codigo: '54109', nombre: 'Bucarasica' },
  { codigoDepartamento: '54', codigo: '54125', nombre: 'Cácota' },
  { codigoDepartamento: '54', codigo: '54128', nombre: 'Cáchira' },
  { codigoDepartamento: '54', codigo: '54172', nombre: 'Chinácota' },
  { codigoDepartamento: '54', codigo: '54174', nombre: 'Chitagá' },
  { codigoDepartamento: '54', codigo: '54206', nombre: 'Convención' },
  { codigoDepartamento: '54', codigo: '54223', nombre: 'Cucutilla' },
  { codigoDepartamento: '54', codigo: '54239', nombre: 'Durania' },
  { codigoDepartamento: '54', codigo: '54245', nombre: 'El Carmen' },
  { codigoDepartamento: '54', codigo: '54250', nombre: 'El Tarra' },
  { codigoDepartamento: '54', codigo: '54261', nombre: 'El Zulia' },
  { codigoDepartamento: '54', codigo: '54313', nombre: 'Gramalote' },
  { codigoDepartamento: '54', codigo: '54344', nombre: 'Hacarí' },
  { codigoDepartamento: '54', codigo: '54347', nombre: 'Herrán' },
  { codigoDepartamento: '54', codigo: '54377', nombre: 'Labateca' },
  { codigoDepartamento: '54', codigo: '54385', nombre: 'La Esperanza' },
  { codigoDepartamento: '54', codigo: '54398', nombre: 'La Playa' },
  { codigoDepartamento: '54', codigo: '54405', nombre: 'Los Patios' },
  { codigoDepartamento: '54', codigo: '54418', nombre: 'Lourdes' },
  { codigoDepartamento: '54', codigo: '54480', nombre: 'Mutiscua' },
  { codigoDepartamento: '54', codigo: '54498', nombre: 'Ocaña' },
  { codigoDepartamento: '54', codigo: '54518', nombre: 'Pamplona' },
  { codigoDepartamento: '54', codigo: '54520', nombre: 'Pamplonita' },
  { codigoDepartamento: '54', codigo: '54553', nombre: 'Puerto Santander' },
  { codigoDepartamento: '54', codigo: '54599', nombre: 'Ragonvalia' },
  { codigoDepartamento: '54', codigo: '54660', nombre: 'Salazar' },
  { codigoDepartamento: '54', codigo: '54670', nombre: 'San Calixto' },
  { codigoDepartamento: '54', codigo: '54673', nombre: 'San Cayetano' },
  { codigoDepartamento: '54', codigo: '54680', nombre: 'Santiago' },
  { codigoDepartamento: '54', codigo: '54720', nombre: 'Sardinata' },
  { codigoDepartamento: '54', codigo: '54743', nombre: 'Silos' },
  { codigoDepartamento: '54', codigo: '54800', nombre: 'Teorama' },
  { codigoDepartamento: '54', codigo: '54810', nombre: 'Tibú' },
  { codigoDepartamento: '54', codigo: '54820', nombre: 'Toledo' },
  { codigoDepartamento: '54', codigo: '54871', nombre: 'Villa Caro' },
  { codigoDepartamento: '54', codigo: '54874', nombre: 'Villa del Rosario' },
  { codigoDepartamento: '63', codigo: '63001', nombre: 'Armenia' },
  { codigoDepartamento: '63', codigo: '63111', nombre: 'Buenavista' },
  { codigoDepartamento: '63', codigo: '63130', nombre: 'Calarcá' },
  { codigoDepartamento: '63', codigo: '63190', nombre: 'Circasia' },
  { codigoDepartamento: '63', codigo: '63212', nombre: 'Córdoba' },
  { codigoDepartamento: '63', codigo: '63272', nombre: 'Filandia' },
  { codigoDepartamento: '63', codigo: '63302', nombre: 'Génova' },
  { codigoDepartamento: '63', codigo: '63401', nombre: 'La Tebaida' },
  { codigoDepartamento: '63', codigo: '63470', nombre: 'Montenegro' },
  { codigoDepartamento: '63', codigo: '63548', nombre: 'Pijao' },
  { codigoDepartamento: '63', codigo: '63594', nombre: 'Quimbaya' },
  { codigoDepartamento: '63', codigo: '63690', nombre: 'Salento' },
  { codigoDepartamento: '66', codigo: '66001', nombre: 'Pereira' },
  { codigoDepartamento: '66', codigo: '66045', nombre: 'Apía' },
  { codigoDepartamento: '66', codigo: '66075', nombre: 'Balboa' },
  { codigoDepartamento: '66', codigo: '66088', nombre: 'Belén de Umbría' },
  { codigoDepartamento: '66', codigo: '66170', nombre: 'Dosquebradas' },
  { codigoDepartamento: '66', codigo: '66318', nombre: 'Guática' },
  { codigoDepartamento: '66', codigo: '66383', nombre: 'La Celia' },
  { codigoDepartamento: '66', codigo: '66400', nombre: 'La Virginia' },
  { codigoDepartamento: '66', codigo: '66440', nombre: 'Marsella' },
  { codigoDepartamento: '66', codigo: '66456', nombre: 'Mistrató' },
  { codigoDepartamento: '66', codigo: '66572', nombre: 'Pueblo Rico' },
  { codigoDepartamento: '66', codigo: '66594', nombre: 'Quinchía' },
  { codigoDepartamento: '66', codigo: '66682', nombre: 'Santa Rosa de Cabal' },
  { codigoDepartamento: '66', codigo: '66687', nombre: 'Santuario' },
  { codigoDepartamento: '68', codigo: '68001', nombre: 'Bucaramanga' },
  { codigoDepartamento: '68', codigo: '68013', nombre: 'Aguada' },
  { codigoDepartamento: '68', codigo: '68020', nombre: 'Albania' },
  { codigoDepartamento: '68', codigo: '68051', nombre: 'Aratoca' },
  { codigoDepartamento: '68', codigo: '68077', nombre: 'Barbosa' },
  { codigoDepartamento: '68', codigo: '68079', nombre: 'Barichara' },
  { codigoDepartamento: '68', codigo: '68081', nombre: 'Barrancabermeja' },
  { codigoDepartamento: '68', codigo: '68092', nombre: 'Betulia' },
  { codigoDepartamento: '68', codigo: '68101', nombre: 'Bolívar' },
  { codigoDepartamento: '68', codigo: '68121', nombre: 'Cabrera' },
  { codigoDepartamento: '68', codigo: '68132', nombre: 'California' },
  { codigoDepartamento: '68', codigo: '68147', nombre: 'Capitanejo' },
  { codigoDepartamento: '68', codigo: '68152', nombre: 'Carcasí' },
  { codigoDepartamento: '68', codigo: '68160', nombre: 'Cepitá' },
  { codigoDepartamento: '68', codigo: '68162', nombre: 'Cerrito' },
  { codigoDepartamento: '68', codigo: '68167', nombre: 'Charalá' },
  { codigoDepartamento: '68', codigo: '68169', nombre: 'Charta' },
  { codigoDepartamento: '68', codigo: '68176', nombre: 'Chima' },
  { codigoDepartamento: '68', codigo: '68179', nombre: 'Chipatá' },
  { codigoDepartamento: '68', codigo: '68190', nombre: 'Cimitarra' },
  { codigoDepartamento: '68', codigo: '68207', nombre: 'Concepción' },
  { codigoDepartamento: '68', codigo: '68209', nombre: 'Confines' },
  { codigoDepartamento: '68', codigo: '68211', nombre: 'Contratación' },
  { codigoDepartamento: '68', codigo: '68217', nombre: 'Coromoro' },
  { codigoDepartamento: '68', codigo: '68229', nombre: 'Curití' },
  { codigoDepartamento: '68', codigo: '68235', nombre: 'El Carmen de Chucurí' },
  { codigoDepartamento: '68', codigo: '68245', nombre: 'El Guacamayo' },
  { codigoDepartamento: '68', codigo: '68250', nombre: 'El Peñón' },
  { codigoDepartamento: '68', codigo: '68255', nombre: 'El Playón' },
  { codigoDepartamento: '68', codigo: '68264', nombre: 'Encino' },
  { codigoDepartamento: '68', codigo: '68266', nombre: 'Enciso' },
  { codigoDepartamento: '68', codigo: '68271', nombre: 'Florián' },
  { codigoDepartamento: '68', codigo: '68276', nombre: 'Floridablanca' },
  { codigoDepartamento: '68', codigo: '68296', nombre: 'Galán' },
  { codigoDepartamento: '68', codigo: '68298', nombre: 'Gámbita' },
  { codigoDepartamento: '68', codigo: '68307', nombre: 'Girón' },
  { codigoDepartamento: '68', codigo: '68318', nombre: 'Guaca' },
  { codigoDepartamento: '68', codigo: '68320', nombre: 'Guadalupe' },
  { codigoDepartamento: '68', codigo: '68322', nombre: 'Guapotá' },
  { codigoDepartamento: '68', codigo: '68324', nombre: 'Guavatá' },
  { codigoDepartamento: '68', codigo: '68327', nombre: 'Güepsa' },
  { codigoDepartamento: '68', codigo: '68344', nombre: 'Hato' },
  { codigoDepartamento: '68', codigo: '68368', nombre: 'Jesús María' },
  { codigoDepartamento: '68', codigo: '68370', nombre: 'Jordán' },
  { codigoDepartamento: '68', codigo: '68377', nombre: 'La Belleza' },
  { codigoDepartamento: '68', codigo: '68385', nombre: 'Landázuri' },
  { codigoDepartamento: '68', codigo: '68397', nombre: 'La Paz' },
  { codigoDepartamento: '68', codigo: '68406', nombre: 'Lebrija' },
  { codigoDepartamento: '68', codigo: '68418', nombre: 'Los Santos' },
  { codigoDepartamento: '68', codigo: '68425', nombre: 'Macaravita' },
  { codigoDepartamento: '68', codigo: '68432', nombre: 'Málaga' },
  { codigoDepartamento: '68', codigo: '68444', nombre: 'Matanza' },
  { codigoDepartamento: '68', codigo: '68464', nombre: 'Mogotes' },
  { codigoDepartamento: '68', codigo: '68468', nombre: 'Molagavita' },
  { codigoDepartamento: '68', codigo: '68498', nombre: 'Ocamonte' },
  { codigoDepartamento: '68', codigo: '68500', nombre: 'Oiba' },
  { codigoDepartamento: '68', codigo: '68502', nombre: 'Onzaga' },
  { codigoDepartamento: '68', codigo: '68522', nombre: 'Palmar' },
  { codigoDepartamento: '68', codigo: '68524', nombre: 'Palmas del Socorro' },
  { codigoDepartamento: '68', codigo: '68533', nombre: 'Páramo' },
  { codigoDepartamento: '68', codigo: '68547', nombre: 'Piedecuesta' },
  { codigoDepartamento: '68', codigo: '68549', nombre: 'Pinchote' },
  { codigoDepartamento: '68', codigo: '68572', nombre: 'Puente Nacional' },
  { codigoDepartamento: '68', codigo: '68573', nombre: 'Puerto Parra' },
  { codigoDepartamento: '68', codigo: '68575', nombre: 'Puerto Wilches' },
  { codigoDepartamento: '68', codigo: '68615', nombre: 'Rionegro' },
  { codigoDepartamento: '68', codigo: '68655', nombre: 'Sabana de Torres' },
  { codigoDepartamento: '68', codigo: '68669', nombre: 'San Andrés' },
  { codigoDepartamento: '68', codigo: '68673', nombre: 'San Benito' },
  { codigoDepartamento: '68', codigo: '68679', nombre: 'San Gil' },
  { codigoDepartamento: '68', codigo: '68682', nombre: 'San Joaquín' },
  { codigoDepartamento: '68', codigo: '68684', nombre: 'San José de Miranda' },
  { codigoDepartamento: '68', codigo: '68686', nombre: 'San Miguel' },
  { codigoDepartamento: '68', codigo: '68689', nombre: 'San Vicente de Chucurí' },
  { codigoDepartamento: '68', codigo: '68705', nombre: 'Santa Bárbara' },
  { codigoDepartamento: '68', codigo: '68720', nombre: 'Santa Helena del Opón' },
  { codigoDepartamento: '68', codigo: '68745', nombre: 'Simacota' },
  { codigoDepartamento: '68', codigo: '68755', nombre: 'Socorro' },
  { codigoDepartamento: '68', codigo: '68770', nombre: 'Suaita' },
  { codigoDepartamento: '68', codigo: '68773', nombre: 'Sucre' },
  { codigoDepartamento: '68', codigo: '68780', nombre: 'Suratá' },
  { codigoDepartamento: '68', codigo: '68820', nombre: 'Tona' },
  { codigoDepartamento: '68', codigo: '68855', nombre: 'Valle de San José' },
  { codigoDepartamento: '68', codigo: '68861', nombre: 'Vélez' },
  { codigoDepartamento: '68', codigo: '68867', nombre: 'Vetas' },
  { codigoDepartamento: '68', codigo: '68872', nombre: 'Villanueva' },
  { codigoDepartamento: '68', codigo: '68895', nombre: 'Zapatoca' },
  { codigoDepartamento: '70', codigo: '70001', nombre: 'Sincelejo' },
  { codigoDepartamento: '70', codigo: '70110', nombre: 'Buenavista' },
  { codigoDepartamento: '70', codigo: '70124', nombre: 'Caimito' },
  { codigoDepartamento: '70', codigo: '70204', nombre: 'Colosó' },
  { codigoDepartamento: '70', codigo: '70215', nombre: 'Corozal' },
  { codigoDepartamento: '70', codigo: '70221', nombre: 'Coveñas' },
  { codigoDepartamento: '70', codigo: '70230', nombre: 'Chalán' },
  { codigoDepartamento: '70', codigo: '70233', nombre: 'El Roble' },
  { codigoDepartamento: '70', codigo: '70235', nombre: 'Galeras' },
  { codigoDepartamento: '70', codigo: '70265', nombre: 'Guaranda' },
  { codigoDepartamento: '70', codigo: '70400', nombre: 'La Unión' },
  { codigoDepartamento: '70', codigo: '70418', nombre: 'Los Palmitos' },
  { codigoDepartamento: '70', codigo: '70429', nombre: 'Majagual' },
  { codigoDepartamento: '70', codigo: '70473', nombre: 'Morroa' },
  { codigoDepartamento: '70', codigo: '70508', nombre: 'Ovejas' },
  { codigoDepartamento: '70', codigo: '70523', nombre: 'Palmito' },
  { codigoDepartamento: '70', codigo: '70670', nombre: 'Sampués' },
  { codigoDepartamento: '70', codigo: '70678', nombre: 'San Benito Abad' },
  { codigoDepartamento: '70', codigo: '70702', nombre: 'San Juan de Betulia' },
  { codigoDepartamento: '70', codigo: '70708', nombre: 'San Marcos' },
  { codigoDepartamento: '70', codigo: '70713', nombre: 'San Onofre' },
  { codigoDepartamento: '70', codigo: '70717', nombre: 'San Pedro' },
  { codigoDepartamento: '70', codigo: '70742', nombre: 'San Luis de Sincé' },
  { codigoDepartamento: '70', codigo: '70771', nombre: 'Sucre' },
  { codigoDepartamento: '70', codigo: '70820', nombre: 'Santiago de Tolú' },
  { codigoDepartamento: '70', codigo: '70823', nombre: 'San José de Toluviejo' },
  { codigoDepartamento: '73', codigo: '73001', nombre: 'Ibagué' },
  { codigoDepartamento: '73', codigo: '73024', nombre: 'Alpujarra' },
  { codigoDepartamento: '73', codigo: '73026', nombre: 'Alvarado' },
  { codigoDepartamento: '73', codigo: '73030', nombre: 'Ambalema' },
  { codigoDepartamento: '73', codigo: '73043', nombre: 'Anzoátegui' },
  { codigoDepartamento: '73', codigo: '73055', nombre: 'Armero' },
  { codigoDepartamento: '73', codigo: '73067', nombre: 'Ataco' },
  { codigoDepartamento: '73', codigo: '73124', nombre: 'Cajamarca' },
  { codigoDepartamento: '73', codigo: '73148', nombre: 'Carmen de Apicalá' },
  { codigoDepartamento: '73', codigo: '73152', nombre: 'Casabianca' },
  { codigoDepartamento: '73', codigo: '73168', nombre: 'Chaparral' },
  { codigoDepartamento: '73', codigo: '73200', nombre: 'Coello' },
  { codigoDepartamento: '73', codigo: '73217', nombre: 'Coyaima' },
  { codigoDepartamento: '73', codigo: '73226', nombre: 'Cunday' },
  { codigoDepartamento: '73', codigo: '73236', nombre: 'Dolores' },
  { codigoDepartamento: '73', codigo: '73268', nombre: 'Espinal' },
  { codigoDepartamento: '73', codigo: '73270', nombre: 'Falan' },
  { codigoDepartamento: '73', codigo: '73275', nombre: 'Flandes' },
  { codigoDepartamento: '73', codigo: '73283', nombre: 'Fresno' },
  { codigoDepartamento: '73', codigo: '73319', nombre: 'Guamo' },
  { codigoDepartamento: '73', codigo: '73347', nombre: 'Herveo' },
  { codigoDepartamento: '73', codigo: '73349', nombre: 'Honda' },
  { codigoDepartamento: '73', codigo: '73352', nombre: 'Icononzo' },
  { codigoDepartamento: '73', codigo: '73408', nombre: 'Lérida' },
  { codigoDepartamento: '73', codigo: '73411', nombre: 'Líbano' },
  { codigoDepartamento: '73', codigo: '73443', nombre: 'San Sebastián de Mariquita' },
  { codigoDepartamento: '73', codigo: '73449', nombre: 'Melgar' },
  { codigoDepartamento: '73', codigo: '73461', nombre: 'Murillo' },
  { codigoDepartamento: '73', codigo: '73483', nombre: 'Natagaima' },
  { codigoDepartamento: '73', codigo: '73504', nombre: 'Ortega' },
  { codigoDepartamento: '73', codigo: '73520', nombre: 'Palocabildo' },
  { codigoDepartamento: '73', codigo: '73547', nombre: 'Piedras' },
  { codigoDepartamento: '73', codigo: '73555', nombre: 'Planadas' },
  { codigoDepartamento: '73', codigo: '73563', nombre: 'Prado' },
  { codigoDepartamento: '73', codigo: '73585', nombre: 'Purificación' },
  { codigoDepartamento: '73', codigo: '73616', nombre: 'Rioblanco' },
  { codigoDepartamento: '73', codigo: '73622', nombre: 'Roncesvalles' },
  { codigoDepartamento: '73', codigo: '73624', nombre: 'Rovira' },
  { codigoDepartamento: '73', codigo: '73671', nombre: 'Saldaña' },
  { codigoDepartamento: '73', codigo: '73675', nombre: 'San Antonio' },
  { codigoDepartamento: '73', codigo: '73678', nombre: 'San Luis' },
  { codigoDepartamento: '73', codigo: '73686', nombre: 'Santa Isabel' },
  { codigoDepartamento: '73', codigo: '73770', nombre: 'Suárez' },
  { codigoDepartamento: '73', codigo: '73854', nombre: 'Valle de San Juan' },
  { codigoDepartamento: '73', codigo: '73861', nombre: 'Venadillo' },
  { codigoDepartamento: '73', codigo: '73870', nombre: 'Villahermosa' },
  { codigoDepartamento: '73', codigo: '73873', nombre: 'Villarrica' },
  { codigoDepartamento: '76', codigo: '76001', nombre: 'Santiago de Cali' },
  { codigoDepartamento: '76', codigo: '76020', nombre: 'Alcalá' },
  { codigoDepartamento: '76', codigo: '76036', nombre: 'Andalucía' },
  { codigoDepartamento: '76', codigo: '76041', nombre: 'Ansermanuevo' },
  { codigoDepartamento: '76', codigo: '76054', nombre: 'Argelia' },
  { codigoDepartamento: '76', codigo: '76100', nombre: 'Bolívar' },
  { codigoDepartamento: '76', codigo: '76109', nombre: 'Buenaventura' },
  { codigoDepartamento: '76', codigo: '76111', nombre: 'Guadalajara de Buga' },
  { codigoDepartamento: '76', codigo: '76113', nombre: 'Bugalagrande' },
  { codigoDepartamento: '76', codigo: '76122', nombre: 'Caicedonia' },
  { codigoDepartamento: '76', codigo: '76126', nombre: 'Calima' },
  { codigoDepartamento: '76', codigo: '76130', nombre: 'Candelaria' },
  { codigoDepartamento: '76', codigo: '76147', nombre: 'Cartago' },
  { codigoDepartamento: '76', codigo: '76233', nombre: 'Dagua' },
  { codigoDepartamento: '76', codigo: '76243', nombre: 'El Águila' },
  { codigoDepartamento: '76', codigo: '76246', nombre: 'El Cairo' },
  { codigoDepartamento: '76', codigo: '76248', nombre: 'El Cerrito' },
  { codigoDepartamento: '76', codigo: '76250', nombre: 'El Dovio' },
  { codigoDepartamento: '76', codigo: '76275', nombre: 'Florida' },
  { codigoDepartamento: '76', codigo: '76306', nombre: 'Ginebra' },
  { codigoDepartamento: '76', codigo: '76318', nombre: 'Guacarí' },
  { codigoDepartamento: '76', codigo: '76364', nombre: 'Jamundí' },
  { codigoDepartamento: '76', codigo: '76377', nombre: 'La Cumbre' },
  { codigoDepartamento: '76', codigo: '76400', nombre: 'La Unión' },
  { codigoDepartamento: '76', codigo: '76403', nombre: 'La Victoria' },
  { codigoDepartamento: '76', codigo: '76497', nombre: 'Obando' },
  { codigoDepartamento: '76', codigo: '76520', nombre: 'Palmira' },
  { codigoDepartamento: '76', codigo: '76563', nombre: 'Pradera' },
  { codigoDepartamento: '76', codigo: '76606', nombre: 'Restrepo' },
  { codigoDepartamento: '76', codigo: '76616', nombre: 'Riofrío' },
  { codigoDepartamento: '76', codigo: '76622', nombre: 'Roldanillo' },
  { codigoDepartamento: '76', codigo: '76670', nombre: 'San Pedro' },
  { codigoDepartamento: '76', codigo: '76736', nombre: 'Sevilla' },
  { codigoDepartamento: '76', codigo: '76823', nombre: 'Toro' },
  { codigoDepartamento: '76', codigo: '76828', nombre: 'Trujillo' },
  { codigoDepartamento: '76', codigo: '76834', nombre: 'Tuluá' },
  { codigoDepartamento: '76', codigo: '76845', nombre: 'Ulloa' },
  { codigoDepartamento: '76', codigo: '76863', nombre: 'Versalles' },
  { codigoDepartamento: '76', codigo: '76869', nombre: 'Vijes' },
  { codigoDepartamento: '76', codigo: '76890', nombre: 'Yotoco' },
  { codigoDepartamento: '76', codigo: '76892', nombre: 'Yumbo' },
  { codigoDepartamento: '76', codigo: '76895', nombre: 'Zarzal' },
  { codigoDepartamento: '81', codigo: '81001', nombre: 'Arauca' },
  { codigoDepartamento: '81', codigo: '81065', nombre: 'Arauquita' },
  { codigoDepartamento: '81', codigo: '81220', nombre: 'Cravo Norte' },
  { codigoDepartamento: '81', codigo: '81300', nombre: 'Fortul' },
  { codigoDepartamento: '81', codigo: '81591', nombre: 'Puerto Rondón' },
  { codigoDepartamento: '81', codigo: '81736', nombre: 'Saravena' },
  { codigoDepartamento: '81', codigo: '81794', nombre: 'Tame' },
  { codigoDepartamento: '85', codigo: '85001', nombre: 'Yopal' },
  { codigoDepartamento: '85', codigo: '85010', nombre: 'Aguazul' },
  { codigoDepartamento: '85', codigo: '85015', nombre: 'Chámeza' },
  { codigoDepartamento: '85', codigo: '85125', nombre: 'Hato Corozal' },
  { codigoDepartamento: '85', codigo: '85136', nombre: 'La Salina' },
  { codigoDepartamento: '85', codigo: '85139', nombre: 'Maní' },
  { codigoDepartamento: '85', codigo: '85162', nombre: 'Monterrey' },
  { codigoDepartamento: '85', codigo: '85225', nombre: 'Nunchía' },
  { codigoDepartamento: '85', codigo: '85230', nombre: 'Orocué' },
  { codigoDepartamento: '85', codigo: '85250', nombre: 'Paz de Ariporo' },
  { codigoDepartamento: '85', codigo: '85263', nombre: 'Pore' },
  { codigoDepartamento: '85', codigo: '85279', nombre: 'Recetor' },
  { codigoDepartamento: '85', codigo: '85300', nombre: 'Sabanalarga' },
  { codigoDepartamento: '85', codigo: '85315', nombre: 'Sácama' },
  { codigoDepartamento: '85', codigo: '85325', nombre: 'San Luis de Palenque' },
  { codigoDepartamento: '85', codigo: '85400', nombre: 'Támara' },
  { codigoDepartamento: '85', codigo: '85410', nombre: 'Tauramena' },
  { codigoDepartamento: '85', codigo: '85430', nombre: 'Trinidad' },
  { codigoDepartamento: '85', codigo: '85440', nombre: 'Villanueva' },
  { codigoDepartamento: '86', codigo: '86001', nombre: 'Mocoa' },
  { codigoDepartamento: '86', codigo: '86219', nombre: 'Colón' },
  { codigoDepartamento: '86', codigo: '86320', nombre: 'Orito' },
  { codigoDepartamento: '86', codigo: '86568', nombre: 'Puerto Asís' },
  { codigoDepartamento: '86', codigo: '86569', nombre: 'Puerto Caicedo' },
  { codigoDepartamento: '86', codigo: '86571', nombre: 'Puerto Guzmán' },
  { codigoDepartamento: '86', codigo: '86573', nombre: 'Puerto Leguízamo' },
  { codigoDepartamento: '86', codigo: '86749', nombre: 'Sibundoy' },
  { codigoDepartamento: '86', codigo: '86755', nombre: 'San Francisco' },
  { codigoDepartamento: '86', codigo: '86757', nombre: 'San Miguel' },
  { codigoDepartamento: '86', codigo: '86760', nombre: 'Santiago' },
  { codigoDepartamento: '86', codigo: '86865', nombre: 'Valle del Guamuez' },
  { codigoDepartamento: '86', codigo: '86885', nombre: 'Villagarzón' },
  { codigoDepartamento: '88', codigo: '88001', nombre: 'San Andrés' },
  { codigoDepartamento: '88', codigo: '88564', nombre: 'Providencia' },
  { codigoDepartamento: '91', codigo: '91001', nombre: 'Leticia' },
  { codigoDepartamento: '91', codigo: '91263', nombre: 'El Encanto' },
  { codigoDepartamento: '91', codigo: '91405', nombre: 'La Chorrera' },
  { codigoDepartamento: '91', codigo: '91407', nombre: 'La Pedrera' },
  { codigoDepartamento: '91', codigo: '91430', nombre: 'La Victoria' },
  { codigoDepartamento: '91', codigo: '91460', nombre: 'Mirití - Paraná' },
  { codigoDepartamento: '91', codigo: '91530', nombre: 'Puerto Alegría' },
  { codigoDepartamento: '91', codigo: '91536', nombre: 'Puerto Arica' },
  { codigoDepartamento: '91', codigo: '91540', nombre: 'Puerto Nariño' },
  { codigoDepartamento: '91', codigo: '91669', nombre: 'Puerto Santander' },
  { codigoDepartamento: '91', codigo: '91798', nombre: 'Tarapacá' },
  { codigoDepartamento: '94', codigo: '94001', nombre: 'Inírida' },
  { codigoDepartamento: '94', codigo: '94343', nombre: 'Barrancominas' },
  { codigoDepartamento: '94', codigo: '94883', nombre: 'San Felipe' },
  { codigoDepartamento: '94', codigo: '94884', nombre: 'Puerto Colombia' },
  { codigoDepartamento: '94', codigo: '94885', nombre: 'La Guadalupe' },
  { codigoDepartamento: '94', codigo: '94886', nombre: 'Cacahual' },
  { codigoDepartamento: '94', codigo: '94887', nombre: 'Pana Pana' },
  { codigoDepartamento: '94', codigo: '94888', nombre: 'Morichal' },
  { codigoDepartamento: '95', codigo: '95001', nombre: 'San José del Guaviare' },
  { codigoDepartamento: '95', codigo: '95015', nombre: 'Calamar' },
  { codigoDepartamento: '95', codigo: '95025', nombre: 'El Retorno' },
  { codigoDepartamento: '95', codigo: '95200', nombre: 'Miraflores' },
  { codigoDepartamento: '97', codigo: '97001', nombre: 'Mitú' },
  { codigoDepartamento: '97', codigo: '97161', nombre: 'Carurú' },
  { codigoDepartamento: '97', codigo: '97511', nombre: 'Pacoa' },
  { codigoDepartamento: '97', codigo: '97666', nombre: 'Taraira' },
  { codigoDepartamento: '97', codigo: '97777', nombre: 'Papunahua' },
  { codigoDepartamento: '97', codigo: '97889', nombre: 'Yavaraté' },
  { codigoDepartamento: '99', codigo: '99001', nombre: 'Puerto Carreño' },
  { codigoDepartamento: '99', codigo: '99524', nombre: 'La Primavera' },
  { codigoDepartamento: '99', codigo: '99624', nombre: 'Santa Rosalía' },
  { codigoDepartamento: '99', codigo: '99773', nombre: 'Cumaribo' },
];
