/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["salud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verFicha"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marcas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AtributoValorRespuesta: {
            nombre?: string;
            valor?: string;
            colorHex?: string;
        };
        CategoriaRespuesta: {
            nombre?: string;
            slug?: string;
            linea?: string;
        };
        DineroRespuesta: {
            /** Format: int64 */
            valor?: number;
            moneda?: string;
        };
        ImagenRespuesta: {
            url?: string;
            urlWebp?: string;
            /** Format: int32 */
            ancho?: number;
            /** Format: int32 */
            alto?: number;
            altEs?: string;
            altEn?: string;
        };
        ImagenRotacionRespuesta: {
            /** Format: int32 */
            orden?: number;
            url?: string;
            urlWebp?: string;
            /** Format: int32 */
            ancho?: number;
            /** Format: int32 */
            alto?: number;
        };
        MarcaRespuesta: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
        };
        ProductoRespuesta: {
            slug?: string;
            nombre?: string;
            descripcion?: string;
            marca?: components["schemas"]["MarcaRespuesta"];
            categoria?: components["schemas"]["CategoriaRespuesta"];
            imagenPrincipal?: components["schemas"]["ImagenRespuesta"];
            galeria?: components["schemas"]["ImagenRespuesta"][];
            rotacion?: components["schemas"]["RotacionRespuesta"];
            variantes?: components["schemas"]["VarianteRespuesta"][];
        };
        ResultadoPaginadoRespuestaProductoRespuesta: {
            items?: components["schemas"]["ProductoRespuesta"][];
            cursorSiguiente?: string;
        };
        RotacionRespuesta: {
            /** Format: int32 */
            fotogramas?: number;
            imagenes?: components["schemas"]["ImagenRotacionRespuesta"][];
        };
        VarianteRespuesta: {
            sku?: string;
            precio?: components["schemas"]["DineroRespuesta"];
            /** Format: int32 */
            existencia?: number;
            atributos?: components["schemas"]["AtributoValorRespuesta"][];
        };
        ResultadoPaginadoRespuestaMarcaRespuesta: {
            items?: components["schemas"]["MarcaRespuesta"][];
            cursorSiguiente?: string;
        };
        ResultadoPaginadoRespuestaCategoriaRespuesta: {
            items?: components["schemas"]["CategoriaRespuesta"][];
            cursorSiguiente?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    buscar: {
        parameters: {
            query?: {
                categoria?: string;
                marca?: string;
                linea?: string;
                precioMin?: number;
                precioMax?: number;
                texto?: string;
                orden?: string;
                cursor?: string;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaProductoRespuesta"];
                };
            };
        };
    };
    verFicha: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductoRespuesta"];
                };
            };
        };
    };
    listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaMarcaRespuesta"];
                };
            };
        };
    };
    listar_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaCategoriaRespuesta"];
                };
            };
        };
    };
}
