/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pedidos/{id}/reintentar-pago": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reintentarPago"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pedidos/metodos-de-pago-disponibles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["metodosDePagoDisponibles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pagos/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pagos/intentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["crear_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carritos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["crear_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carritos/{id}/lineas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agregarLinea"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["iniciarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresco": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refrescar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cierre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cerrarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/verificar-contraentrega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verificar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/rechazo-entrega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rechazarEnEntrega"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/recaudo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["conciliarRecaudo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/entrega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["marcarEntregado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/despacho": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["despachar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/conciliar-transferencia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["conciliar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cobertura-contraentrega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agregar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pagos/intentos/{referencia}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["registrarIdTransaccion"];
        trace?: never;
    };
    "/api/v1/carritos/{id}/lineas/{lineaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["eliminarLinea"];
        options?: never;
        head?: never;
        patch: operations["actualizarCantidad"];
        trace?: never;
    };
    "/api/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["salud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verFicha"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pedidos/{id}/seguimiento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["seguimiento"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marcas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/envios/cobertura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carritos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cobertura-contraentrega/{codigoDaneCiudad}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["quitar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CrearPedidoRequest: {
            correo?: string;
            lineas?: components["schemas"]["LineaRequest"][];
            tipoEntrega?: string;
            direccion?: components["schemas"]["DireccionRequest"];
            metodoPago?: string;
        };
        DireccionRequest: {
            codigoDaneDepartamento?: string;
            departamento?: string;
            codigoDaneCiudad?: string;
            ciudad?: string;
            direccion?: string;
            indicaciones?: string;
        };
        LineaRequest: {
            /** Format: uuid */
            varianteId?: string;
            /** Format: int32 */
            cantidad?: number;
        };
        DatosTransferenciaRespuesta: {
            banco?: string;
            tipoCuenta?: string;
            numeroCuenta?: string;
            titular?: string;
            referencia?: string;
        };
        DineroRespuesta: {
            /** Format: int64 */
            valor?: number;
            moneda?: string;
        };
        DireccionRespuesta: {
            codigoDaneDepartamento?: string;
            departamento?: string;
            codigoDaneCiudad?: string;
            ciudad?: string;
            direccion?: string;
            indicaciones?: string;
        };
        LineaPedidoRespuesta: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            varianteId?: string;
            sku?: string;
            nombre?: string;
            /** Format: int32 */
            cantidad?: number;
            precioUnitario?: components["schemas"]["DineroRespuesta"];
            tasaIva?: number;
            imagenUrl?: string;
        };
        PedidoRespuesta: {
            /** Format: uuid */
            id?: string;
            numeroPedido?: string;
            /** Format: uuid */
            usuarioId?: string;
            correo?: string;
            lineas?: components["schemas"]["LineaPedidoRespuesta"][];
            tipoEntrega?: string;
            direccion?: components["schemas"]["DireccionRespuesta"];
            metodoPago?: string;
            estado?: string;
            total?: components["schemas"]["DineroRespuesta"];
            /** Format: date-time */
            creadoEn?: string;
            datosTransferencia?: components["schemas"]["DatosTransferenciaRespuesta"];
        };
        MetodosDePagoDisponiblesRequest: {
            lineas?: components["schemas"]["LineaRequest"][];
            correo?: string;
            tipoEntrega?: string;
            direccion?: components["schemas"]["DireccionRequest"];
        };
        JsonNode: {
            number?: boolean;
            missingNode?: boolean;
            /** @enum {string} */
            nodeType?: "ARRAY" | "BINARY" | "BOOLEAN" | "MISSING" | "NULL" | "NUMBER" | "OBJECT" | "POJO" | "STRING";
            bigDecimal?: boolean;
            bigInteger?: boolean;
            valueNode?: boolean;
            integralNumber?: boolean;
            container?: boolean;
            object?: boolean;
            string?: boolean;
            double?: boolean;
            long?: boolean;
            pojo?: boolean;
            binary?: boolean;
            int?: boolean;
            short?: boolean;
            boolean?: boolean;
            /** @deprecated */
            textual?: boolean;
            floatingPointNumber?: boolean;
            array?: boolean;
            empty?: boolean;
            null?: boolean;
            float?: boolean;
            embeddedValue?: boolean;
        };
        CrearIntentoDePagoRequest: {
            /** Format: uuid */
            pedidoId?: string;
        };
        IntentoDePagoRespuesta: {
            referencia?: string;
            monto?: components["schemas"]["DineroRespuesta"];
            firmaIntegridad?: string;
            llavePublica?: string;
            ambiente?: string;
        };
        CarritoRespuesta: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            usuarioId?: string;
            lineas?: components["schemas"]["LineaCarritoRespuesta"][];
            /** Format: date-time */
            creadoEn?: string;
        };
        LineaCarritoRespuesta: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            varianteId?: string;
            /** Format: int32 */
            cantidad?: number;
        };
        AgregarLineaRequest: {
            /** Format: uuid */
            varianteId?: string;
            /** Format: int32 */
            cantidad?: number;
        };
        IniciarSesionRequest: {
            correo?: string;
            clave?: string;
        };
        SesionRespuesta: {
            /** Format: uuid */
            usuarioId?: string;
            rol?: string;
            accessToken?: string;
        };
        VerificarContraentregaRequest: {
            motivo?: string;
        };
        RechazarEnEntregaRequest: {
            motivo?: string;
        };
        ConciliarRecaudoRequest: {
            /** Format: int64 */
            comisionRecaudo?: number;
        };
        DespacharPedidoRequest: {
            transportadora?: string;
            guia?: string;
            /** Format: int64 */
            costoEnvio?: number;
        };
        CoberturaContraentregaRequest: {
            codigoDaneCiudad?: string;
        };
        RegistrarIdTransaccionWompiRequest: {
            idTransaccionWompi?: string;
        };
        ActualizarCantidadRequest: {
            /** Format: int32 */
            cantidad?: number;
        };
        AtributoValorRespuesta: {
            nombre?: string;
            valor?: string;
            colorHex?: string;
        };
        CategoriaRespuesta: {
            nombre?: string;
            slug?: string;
            linea?: string;
        };
        ImagenRespuesta: {
            url?: string;
            urlWebp?: string;
            /** Format: int32 */
            ancho?: number;
            /** Format: int32 */
            alto?: number;
            altEs?: string;
            altEn?: string;
        };
        ImagenRotacionRespuesta: {
            /** Format: int32 */
            orden?: number;
            url?: string;
            urlWebp?: string;
            /** Format: int32 */
            ancho?: number;
            /** Format: int32 */
            alto?: number;
        };
        MarcaRespuesta: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
        };
        ProductoRespuesta: {
            slug?: string;
            nombre?: string;
            descripcion?: string;
            marca?: components["schemas"]["MarcaRespuesta"];
            categoria?: components["schemas"]["CategoriaRespuesta"];
            imagenPrincipal?: components["schemas"]["ImagenRespuesta"];
            galeria?: components["schemas"]["ImagenRespuesta"][];
            rotacion?: components["schemas"]["RotacionRespuesta"];
            variantes?: components["schemas"]["VarianteRespuesta"][];
        };
        ResultadoPaginadoRespuestaProductoRespuesta: {
            items?: components["schemas"]["ProductoRespuesta"][];
            cursorSiguiente?: string;
        };
        RotacionRespuesta: {
            /** Format: int32 */
            fotogramas?: number;
            imagenes?: components["schemas"]["ImagenRotacionRespuesta"][];
        };
        VarianteRespuesta: {
            /** Format: uuid */
            id?: string;
            sku?: string;
            precio?: components["schemas"]["DineroRespuesta"];
            /** Format: int32 */
            existencia?: number;
            atributos?: components["schemas"]["AtributoValorRespuesta"][];
        };
        ResultadoPaginadoRespuestaMarcaRespuesta: {
            items?: components["schemas"]["MarcaRespuesta"][];
            cursorSiguiente?: string;
        };
        ResultadoPaginadoRespuestaCategoriaRespuesta: {
            items?: components["schemas"]["CategoriaRespuesta"][];
            cursorSiguiente?: string;
        };
        PedidosPaginadosRespuesta: {
            items?: components["schemas"]["PedidoRespuesta"][];
            /** Format: int32 */
            pagina?: number;
            /** Format: int32 */
            totalPaginas?: number;
            /** Format: int64 */
            totalPedidos?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearPedidoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    reintentarPago: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    metodosDePagoDisponibles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetodosDePagoDisponiblesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonNode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crear_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearIntentoDePagoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IntentoDePagoRespuesta"];
                };
            };
        };
    };
    crear_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    agregarLinea: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgregarLineaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    iniciarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IniciarSesionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionRespuesta"];
                };
            };
        };
    };
    refrescar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresco?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionRespuesta"];
                };
            };
        };
    };
    cerrarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresco?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verificar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificarContraentregaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    rechazarEnEntrega: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RechazarEnEntregaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    conciliarRecaudo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConciliarRecaudoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    marcarEntregado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    despachar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DespacharPedidoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    conciliar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    agregar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoberturaContraentregaRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registrarIdTransaccion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referencia: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarIdTransaccionWompiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eliminarLinea: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                lineaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    actualizarCantidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                lineaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarCantidadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    salud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    buscar: {
        parameters: {
            query?: {
                categoria?: string;
                marca?: string;
                linea?: string;
                precioMin?: number;
                precioMax?: number;
                texto?: string;
                orden?: string;
                cursor?: string;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaProductoRespuesta"];
                };
            };
        };
    };
    verFicha: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductoRespuesta"];
                };
            };
        };
    };
    seguimiento: {
        parameters: {
            query: {
                correo: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    listar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaMarcaRespuesta"];
                };
            };
        };
    };
    listar_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    listar_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaCategoriaRespuesta"];
                };
            };
        };
    };
    ver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    listar_3: {
        parameters: {
            query?: {
                pagina?: number;
                tamano?: number;
                estado?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidosPaginadosRespuesta"];
                };
            };
        };
    };
    quitar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigoDaneCiudad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
