/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["crear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pedidos/{id}/reintentar-pago": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reintentarPago"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pedidos/metodos-de-pago-disponibles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["metodosDePagoDisponibles"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pagos/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pagos/intentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["crear_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carritos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["crear_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carritos/{id}/lineas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agregarLinea"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/verificacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verificacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["iniciarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/registro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registro"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresco": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refrescar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recuperacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recuperacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/recuperacion/confirmar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmarRecuperacion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cierre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cerrarSesion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/variantes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["crear_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sets-rotacion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["abrir"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sets-rotacion/{id}/subidas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["subidas"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sets-rotacion/{id}/publicar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publicar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sets-rotacion/{id}/completar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/retractos/{id}/reembolso": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reembolsar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/retractos/{id}/recepcion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["recibirProducto"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar"];
        put?: never;
        post: operations["crear_4"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/productos/{id}/imagen-principal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmarImagenPrincipal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/productos/{id}/imagen-principal/url-subida": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["solicitarUrlDeSubida"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{pedidoId}/retractos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_1"];
        put?: never;
        post: operations["radicar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/verificar-contraentrega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verificar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/rechazo-entrega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rechazarEnEntrega"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/recaudo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["conciliarRecaudo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/entrega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["marcarEntregado"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/despacho": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["despachar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos/{id}/conciliar-transferencia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["conciliar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cobertura-contraentrega": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["agregar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pagos/intentos/{referencia}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["registrarIdTransaccion"];
        trace?: never;
    };
    "/api/v1/carritos/{id}/lineas/{lineaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["eliminarLinea"];
        options?: never;
        head?: never;
        patch: operations["actualizarCantidad"];
        trace?: never;
    };
    "/api/v1/admin/productos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ver"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["editar"];
        trace?: never;
    };
    "/api/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["salud"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/productos/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["verFicha"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pedidos/{id}/seguimiento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["seguimiento"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/marcas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mapa-del-sitio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ver_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/envios/cobertura": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/categorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/carritos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ver_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/atributos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/pedidos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listar_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/sets-rotacion/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["eliminar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/cobertura-contraentrega/{codigoDaneCiudad}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["quitar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CrearPedidoRequest: {
            correo?: string;
            lineas?: components["schemas"]["LineaRequest"][];
            tipoEntrega?: string;
            direccion?: components["schemas"]["DireccionRequest"];
            metodoPago?: string;
            autorizaDatos?: boolean;
        };
        DireccionRequest: {
            codigoDaneDepartamento?: string;
            departamento?: string;
            codigoDaneCiudad?: string;
            ciudad?: string;
            direccion?: string;
            indicaciones?: string;
        };
        LineaRequest: {
            /** Format: uuid */
            varianteId?: string;
            /** Format: int32 */
            cantidad?: number;
        };
        DatosTransferenciaRespuesta: {
            banco?: string;
            tipoCuenta?: string;
            numeroCuenta?: string;
            titular?: string;
            referencia?: string;
        };
        DineroRespuesta: {
            /** Format: int64 */
            valor?: number;
            moneda?: string;
        };
        DireccionRespuesta: {
            codigoDaneDepartamento?: string;
            departamento?: string;
            codigoDaneCiudad?: string;
            ciudad?: string;
            direccion?: string;
            indicaciones?: string;
        };
        EnvioRespuesta: {
            transportadora?: string;
            guia?: string;
            costoEnvio?: components["schemas"]["DineroRespuesta"];
            /** Format: date-time */
            despachadoEn?: string;
            comisionRecaudo?: components["schemas"]["DineroRespuesta"];
            /** Format: date-time */
            recaudoConciliadoEn?: string;
        };
        HistorialPedidoRespuesta: {
            estado?: string;
            /** Format: date-time */
            fecha?: string;
            actor?: string;
            motivo?: string;
        };
        LineaPedidoRespuesta: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            varianteId?: string;
            sku?: string;
            nombre?: string;
            /** Format: int32 */
            cantidad?: number;
            precioUnitario?: components["schemas"]["DineroRespuesta"];
            tasaIva?: number;
            imagenUrl?: string;
        };
        PedidoRespuesta: {
            /** Format: uuid */
            id?: string;
            numeroPedido?: string;
            /** Format: uuid */
            usuarioId?: string;
            correo?: string;
            lineas?: components["schemas"]["LineaPedidoRespuesta"][];
            tipoEntrega?: string;
            direccion?: components["schemas"]["DireccionRespuesta"];
            metodoPago?: string;
            estado?: string;
            total?: components["schemas"]["DineroRespuesta"];
            /** Format: date-time */
            creadoEn?: string;
            datosTransferencia?: components["schemas"]["DatosTransferenciaRespuesta"];
            envio?: components["schemas"]["EnvioRespuesta"];
            historial?: components["schemas"]["HistorialPedidoRespuesta"][];
        };
        MetodosDePagoDisponiblesRequest: {
            lineas?: components["schemas"]["LineaRequest"][];
            correo?: string;
            tipoEntrega?: string;
            direccion?: components["schemas"]["DireccionRequest"];
        };
        CrearIntentoDePagoRequest: {
            /** Format: uuid */
            pedidoId?: string;
        };
        IntentoDePagoRespuesta: {
            referencia?: string;
            monto?: components["schemas"]["DineroRespuesta"];
            firmaIntegridad?: string;
            llavePublica?: string;
            ambiente?: string;
        };
        CarritoRespuesta: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            usuarioId?: string;
            lineas?: components["schemas"]["LineaCarritoRespuesta"][];
            /** Format: date-time */
            creadoEn?: string;
        };
        LineaCarritoRespuesta: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            varianteId?: string;
            /** Format: int32 */
            cantidad?: number;
        };
        AgregarLineaRequest: {
            /** Format: uuid */
            varianteId?: string;
            /** Format: int32 */
            cantidad?: number;
        };
        VerificarCorreoRequest: {
            token?: string;
        };
        IniciarSesionRequest: {
            correo?: string;
            clave?: string;
        };
        SesionRespuesta: {
            /** Format: uuid */
            usuarioId?: string;
            rol?: string;
            accessToken?: string;
        };
        RegistrarUsuarioRequest: {
            correo?: string;
            clave?: string;
            autorizaDatos?: boolean;
        };
        SolicitarRecuperacionRequest: {
            correo?: string;
        };
        ConfirmarRecuperacionRequest: {
            token?: string;
            claveNueva?: string;
        };
        AgregarVariantePeticion: {
            /** Format: uuid */
            productoId?: string;
            sku?: string;
            /** Format: int64 */
            precio?: number;
            tasaIva?: number;
            codigoBarras?: string;
            /** Format: int32 */
            existenciaInicial?: number;
            atributos?: components["schemas"]["ValorAtributoPeticion"][];
        };
        ValorAtributoPeticion: {
            /** Format: uuid */
            atributoId?: string;
            valor?: string;
            colorHex?: string;
        };
        AtributoValorRespuesta: {
            nombre?: string;
            valor?: string;
            colorHex?: string;
        };
        VarianteRespuesta: {
            /** Format: uuid */
            id?: string;
            sku?: string;
            precio?: components["schemas"]["DineroRespuesta"];
            /** Format: int32 */
            existencia?: number;
            atributos?: components["schemas"]["AtributoValorRespuesta"][];
        };
        AbrirSetRotacionPeticion: {
            /** Format: uuid */
            productoId?: string;
            /** Format: int32 */
            fotogramas?: number;
            dispositivo?: string;
            versionAsistente?: string;
        };
        ImagenRotacionRespuesta: {
            /** Format: int32 */
            orden?: number;
            url?: string;
            urlWebp?: string;
            /** Format: int32 */
            ancho?: number;
            /** Format: int32 */
            alto?: number;
        };
        SetRotacionRespuesta: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            productoId?: string;
            /** Format: int32 */
            fotogramasPrometidos?: number;
            estado?: string;
            capturadoPor?: string;
            /** Format: date-time */
            capturadoEn?: string;
            dispositivo?: string;
            versionAsistente?: string;
            imagenes?: components["schemas"]["ImagenRotacionRespuesta"][];
        };
        SolicitarSubidasDeRotacionPeticion: {
            contentType?: string;
        };
        SubidaDeFotogramaRespuesta: {
            /** Format: int32 */
            orden?: number;
            url?: string;
            objectKey?: string;
        };
        CompletarSetRotacionPeticion: {
            fotogramas?: components["schemas"]["FotogramaPeticion"][];
        };
        FotogramaPeticion: {
            /** Format: int32 */
            orden?: number;
            objectKey?: string;
            /** Format: int32 */
            ancho?: number;
            /** Format: int32 */
            alto?: number;
            hash?: string;
        };
        RegistrarReembolsoRequest: {
            monto?: number;
            medio?: string;
            comprobante?: string;
        };
        ReembolsoRespuesta: {
            monto?: number;
            medio?: string;
            comprobante?: string;
            /** Format: date-time */
            registradoEn?: string;
            registradoPor?: string;
        };
        SolicitudRetractoRespuesta: {
            id?: string;
            pedidoId?: string;
            /** Format: date-time */
            radicadaEn?: string;
            radicadaPor?: string;
            motivo?: string;
            verdictoAlRadicar?: string;
            estado?: string;
            /** Format: date-time */
            productoRecibidoEn?: string;
            /** Format: date-time */
            limiteDeReintegro?: string;
            reembolso?: components["schemas"]["ReembolsoRespuesta"];
        };
        CrearProductoPeticion: {
            nombre?: string;
            descripcion?: string;
            /** Format: uuid */
            marcaId?: string;
            /** Format: uuid */
            categoriaId?: string;
        };
        CategoriaRespuesta: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
            slug?: string;
            linea?: string;
        };
        MarcaRespuesta: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
        };
        ProductoAdminRespuesta: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
            descripcion?: string;
            slug?: string;
            estado?: string;
            marca?: components["schemas"]["MarcaRespuesta"];
            categoria?: components["schemas"]["CategoriaRespuesta"];
            imagenPrincipalUrl?: string;
            /** Format: int32 */
            totalVariantes?: number;
        };
        ConfirmarImagenPrincipalPeticion: {
            objectKey?: string;
            /** Format: int32 */
            ancho?: number;
            /** Format: int32 */
            alto?: number;
            hash?: string;
            altEs?: string;
            altEn?: string;
        };
        ImagenRespuesta: {
            url?: string;
            urlWebp?: string;
            /** Format: int32 */
            ancho?: number;
            /** Format: int32 */
            alto?: number;
            altEs?: string;
            altEn?: string;
        };
        SolicitarSubidaDeImagenPrincipalPeticion: {
            contentType?: string;
        };
        UrlSubidaRespuesta: {
            url?: string;
            objectKey?: string;
        };
        RegistrarRetractoRequest: {
            motivo?: string;
        };
        VerificarContraentregaRequest: {
            motivo?: string;
        };
        RechazarEnEntregaRequest: {
            motivo?: string;
        };
        ConciliarRecaudoRequest: {
            /** Format: int64 */
            comisionRecaudo?: number;
        };
        DespacharPedidoRequest: {
            transportadora?: string;
            guia?: string;
            /** Format: int64 */
            costoEnvio?: number;
        };
        CoberturaContraentregaRequest: {
            codigoDaneCiudad?: string;
        };
        RegistrarIdTransaccionWompiRequest: {
            idTransaccionWompi?: string;
        };
        ActualizarCantidadRequest: {
            /** Format: int32 */
            cantidad?: number;
        };
        EditarProductoPeticion: {
            nombre?: string;
            descripcion?: string;
            /** Format: uuid */
            marcaId?: string;
            /** Format: uuid */
            categoriaId?: string;
        };
        ProductoRespuesta: {
            slug?: string;
            nombre?: string;
            descripcion?: string;
            marca?: components["schemas"]["MarcaRespuesta"];
            categoria?: components["schemas"]["CategoriaRespuesta"];
            imagenPrincipal?: components["schemas"]["ImagenRespuesta"];
            galeria?: components["schemas"]["ImagenRespuesta"][];
            rotacion?: components["schemas"]["RotacionRespuesta"];
            variantes?: components["schemas"]["VarianteRespuesta"][];
        };
        ResultadoPaginadoRespuestaProductoRespuesta: {
            items?: components["schemas"]["ProductoRespuesta"][];
            cursorSiguiente?: string;
        };
        RotacionRespuesta: {
            /** Format: int32 */
            fotogramas?: number;
            imagenes?: components["schemas"]["ImagenRotacionRespuesta"][];
        };
        ResultadoPaginadoRespuestaMarcaRespuesta: {
            items?: components["schemas"]["MarcaRespuesta"][];
            cursorSiguiente?: string;
        };
        MapaDelSitioRespuesta: {
            productos?: components["schemas"]["Producto"][];
        };
        Producto: {
            slug?: string;
            /** Format: date-time */
            actualizadoEn?: string;
        };
        ResultadoPaginadoRespuestaCategoriaRespuesta: {
            items?: components["schemas"]["CategoriaRespuesta"][];
            cursorSiguiente?: string;
        };
        AtributoRespuesta: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
            tipo?: string;
            valoresPermitidos?: string[];
        };
        ResultadoPaginadoRespuestaAtributoRespuesta: {
            items?: components["schemas"]["AtributoRespuesta"][];
            cursorSiguiente?: string;
        };
        ProductosAdminPaginadosRespuesta: {
            items?: components["schemas"]["ProductoAdminRespuesta"][];
            /** Format: int32 */
            pagina?: number;
            /** Format: int32 */
            totalPaginas?: number;
            /** Format: int64 */
            totalProductos?: number;
        };
        PedidosPaginadosRespuesta: {
            items?: components["schemas"]["PedidoRespuesta"][];
            /** Format: int32 */
            pagina?: number;
            /** Format: int32 */
            totalPaginas?: number;
            /** Format: int64 */
            totalPedidos?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    crear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearPedidoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    reintentarPago: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    metodosDePagoDisponibles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetodosDePagoDisponiblesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Evento de Wompi, tal como lo envía la pasarela. Se valida por firma. */
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crear_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearIntentoDePagoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IntentoDePagoRespuesta"];
                };
            };
        };
    };
    crear_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    agregarLinea: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgregarLineaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    verificacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificarCorreoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    iniciarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IniciarSesionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionRespuesta"];
                };
            };
        };
    };
    registro: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarUsuarioRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    refrescar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresco?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Sesión refrescada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SesionRespuesta"];
                };
            };
            /** @description No hay cookie de refresco: no hay sesión que refrescar */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recuperacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitarRecuperacionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    confirmarRecuperacion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmarRecuperacionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    cerrarSesion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                refresco?: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    crear_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgregarVariantePeticion"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["VarianteRespuesta"];
                };
            };
        };
    };
    abrir: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbrirSetRotacionPeticion"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetRotacionRespuesta"];
                };
            };
        };
    };
    subidas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitarSubidasDeRotacionPeticion"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SubidaDeFotogramaRespuesta"][];
                };
            };
        };
    };
    publicar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetRotacionRespuesta"];
                };
            };
        };
    };
    completar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompletarSetRotacionPeticion"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SetRotacionRespuesta"];
                };
            };
        };
    };
    reembolsar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarReembolsoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudRetractoRespuesta"];
                };
            };
        };
    };
    recibirProducto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudRetractoRespuesta"];
                };
            };
        };
    };
    listar: {
        parameters: {
            query?: {
                pagina?: number;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductosAdminPaginadosRespuesta"];
                };
            };
        };
    };
    crear_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CrearProductoPeticion"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductoAdminRespuesta"];
                };
            };
        };
    };
    confirmarImagenPrincipal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmarImagenPrincipalPeticion"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImagenRespuesta"];
                };
            };
        };
    };
    solicitarUrlDeSubida: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolicitarSubidaDeImagenPrincipalPeticion"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UrlSubidaRespuesta"];
                };
            };
        };
    };
    listar_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedidoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudRetractoRespuesta"][];
                };
            };
        };
    };
    radicar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pedidoId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RegistrarRetractoRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SolicitudRetractoRespuesta"];
                };
            };
        };
    };
    verificar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerificarContraentregaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    rechazarEnEntrega: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RechazarEnEntregaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    conciliarRecaudo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConciliarRecaudoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    marcarEntregado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    despachar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DespacharPedidoRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    conciliar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    agregar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoberturaContraentregaRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registrarIdTransaccion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referencia: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegistrarIdTransaccionWompiRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    eliminarLinea: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                lineaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    actualizarCantidad: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                lineaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActualizarCantidadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    ver: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductoAdminRespuesta"];
                };
            };
        };
    };
    editar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditarProductoPeticion"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductoAdminRespuesta"];
                };
            };
        };
    };
    salud: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    buscar: {
        parameters: {
            query?: {
                categoria?: string;
                marca?: string;
                linea?: string;
                precioMin?: number;
                precioMax?: number;
                texto?: string;
                orden?: string;
                cursor?: string;
                tamano?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaProductoRespuesta"];
                };
            };
        };
    };
    verFicha: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductoRespuesta"];
                };
            };
        };
    };
    seguimiento: {
        parameters: {
            query: {
                correo: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidoRespuesta"];
                };
            };
        };
    };
    listar_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaMarcaRespuesta"];
                };
            };
        };
    };
    ver_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MapaDelSitioRespuesta"];
                };
            };
        };
    };
    listar_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string[];
                };
            };
        };
    };
    listar_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaCategoriaRespuesta"];
                };
            };
        };
    };
    ver_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CarritoRespuesta"];
                };
            };
        };
    };
    listar_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResultadoPaginadoRespuestaAtributoRespuesta"];
                };
            };
        };
    };
    listar_6: {
        parameters: {
            query?: {
                pagina?: number;
                tamano?: number;
                estado?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PedidosPaginadosRespuesta"];
                };
            };
        };
    };
    eliminar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    quitar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codigoDaneCiudad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
